/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.shape.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Dimension
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "default",
    "facet",
    "gated-by",
    "id",
    "operator",
    "path",
    "points"
})
public class Dimension {

    /**
     * Name of the point the shape's own examples exercise — the base variant's assignment for this dimension.
     * (Required)
     * 
     */
    @JsonProperty("default")
    @JsonPropertyDescription("Name of the point the shape's own examples exercise \u2014 the base variant's assignment for this dimension.")
    private String _default;
    /**
     * Which axis of the located value varies. Open vocabulary: a component operator may contribute its own.
     * (Required)
     * 
     */
    @JsonProperty("facet")
    @JsonPropertyDescription("Which axis of the located value varies. Open vocabulary: a component operator may contribute its own.")
    private String facet;
    /**
     * Points that must all be selected for this dimension to be active. Absent or empty means always active (spec.md §6.3).
     * 
     */
    @JsonProperty("gated-by")
    @JsonPropertyDescription("Points that must all be selected for this dimension to be active. Absent or empty means always active (spec.md \u00a76.3).")
    private List<Gate> gatedBy;
    /**
     * '<path>#<facet>', stable across engine versions and pact-file round trips (spec.md §6.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    @JsonPropertyDescription("'<path>#<facet>', stable across engine versions and pact-file round trips (spec.md \u00a76.2).")
    private String id;
    /**
     * The shape operator that contributed the dimension.
     * 
     */
    @JsonProperty("operator")
    @JsonPropertyDescription("The shape operator that contributed the dimension.")
    private String operator;
    /**
     * The location of the operator that contributes the dimension, without the facet suffix.
     * 
     */
    @JsonProperty("path")
    @JsonPropertyDescription("The location of the operator that contributes the dimension, without the facet suffix.")
    private String path;
    /**
     * The values this dimension can take. A dimension with fewer than two points is not a dimension (spec.md §6.1).
     * (Required)
     * 
     */
    @JsonProperty("points")
    @JsonPropertyDescription("The values this dimension can take. A dimension with fewer than two points is not a dimension (spec.md \u00a76.1).")
    private List<Point> points;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Name of the point the shape's own examples exercise — the base variant's assignment for this dimension.
     * (Required)
     * 
     */
    @JsonProperty("default")
    public String getDefault() {
        return _default;
    }

    /**
     * Name of the point the shape's own examples exercise — the base variant's assignment for this dimension.
     * (Required)
     * 
     */
    @JsonProperty("default")
    public void setDefault(String _default) {
        this._default = _default;
    }

    /**
     * Which axis of the located value varies. Open vocabulary: a component operator may contribute its own.
     * (Required)
     * 
     */
    @JsonProperty("facet")
    public String getFacet() {
        return facet;
    }

    /**
     * Which axis of the located value varies. Open vocabulary: a component operator may contribute its own.
     * (Required)
     * 
     */
    @JsonProperty("facet")
    public void setFacet(String facet) {
        this.facet = facet;
    }

    /**
     * Points that must all be selected for this dimension to be active. Absent or empty means always active (spec.md §6.3).
     * 
     */
    @JsonProperty("gated-by")
    public List<Gate> getGatedBy() {
        return gatedBy;
    }

    /**
     * Points that must all be selected for this dimension to be active. Absent or empty means always active (spec.md §6.3).
     * 
     */
    @JsonProperty("gated-by")
    public void setGatedBy(List<Gate> gatedBy) {
        this.gatedBy = gatedBy;
    }

    /**
     * '<path>#<facet>', stable across engine versions and pact-file round trips (spec.md §6.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * '<path>#<facet>', stable across engine versions and pact-file round trips (spec.md §6.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * The shape operator that contributed the dimension.
     * 
     */
    @JsonProperty("operator")
    public String getOperator() {
        return operator;
    }

    /**
     * The shape operator that contributed the dimension.
     * 
     */
    @JsonProperty("operator")
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * The location of the operator that contributes the dimension, without the facet suffix.
     * 
     */
    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    /**
     * The location of the operator that contributes the dimension, without the facet suffix.
     * 
     */
    @JsonProperty("path")
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * The values this dimension can take. A dimension with fewer than two points is not a dimension (spec.md §6.1).
     * (Required)
     * 
     */
    @JsonProperty("points")
    public List<Point> getPoints() {
        return points;
    }

    /**
     * The values this dimension can take. A dimension with fewer than two points is not a dimension (spec.md §6.1).
     * (Required)
     * 
     */
    @JsonProperty("points")
    public void setPoints(List<Point> points) {
        this.points = points;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Dimension.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("_default");
        sb.append('=');
        sb.append(((this._default == null)?"<null>":this._default));
        sb.append(',');
        sb.append("facet");
        sb.append('=');
        sb.append(((this.facet == null)?"<null>":this.facet));
        sb.append(',');
        sb.append("gatedBy");
        sb.append('=');
        sb.append(((this.gatedBy == null)?"<null>":this.gatedBy));
        sb.append(',');
        sb.append("id");
        sb.append('=');
        sb.append(((this.id == null)?"<null>":this.id));
        sb.append(',');
        sb.append("operator");
        sb.append('=');
        sb.append(((this.operator == null)?"<null>":this.operator));
        sb.append(',');
        sb.append("path");
        sb.append('=');
        sb.append(((this.path == null)?"<null>":this.path));
        sb.append(',');
        sb.append("points");
        sb.append('=');
        sb.append(((this.points == null)?"<null>":this.points));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this._default == null)? 0 :this._default.hashCode()));
        result = ((result* 31)+((this.path == null)? 0 :this.path.hashCode()));
        result = ((result* 31)+((this.gatedBy == null)? 0 :this.gatedBy.hashCode()));
        result = ((result* 31)+((this.id == null)? 0 :this.id.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.facet == null)? 0 :this.facet.hashCode()));
        result = ((result* 31)+((this.operator == null)? 0 :this.operator.hashCode()));
        result = ((result* 31)+((this.points == null)? 0 :this.points.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Dimension) == false) {
            return false;
        }
        Dimension rhs = ((Dimension) other);
        return (((((((((this._default == rhs._default)||((this._default!= null)&&this._default.equals(rhs._default)))&&((this.path == rhs.path)||((this.path!= null)&&this.path.equals(rhs.path))))&&((this.gatedBy == rhs.gatedBy)||((this.gatedBy!= null)&&this.gatedBy.equals(rhs.gatedBy))))&&((this.id == rhs.id)||((this.id!= null)&&this.id.equals(rhs.id))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.facet == rhs.facet)||((this.facet!= null)&&this.facet.equals(rhs.facet))))&&((this.operator == rhs.operator)||((this.operator!= null)&&this.operator.equals(rhs.operator))))&&((this.points == rhs.points)||((this.points!= null)&&this.points.equals(rhs.points))));
    }

}
