/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.shape.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Point
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "name",
    "size",
    "value"
})
public class Point {

    /**
     * Stable within the dimension: 'present'/'absent', 'null'/'non-null', an alternative name, a canonical literal rendering, or 'min'/'min+1'/'max'.
     * (Required)
     * 
     */
    @JsonProperty("name")
    @JsonPropertyDescription("Stable within the dimension: 'present'/'absent', 'null'/'non-null', an alternative name, a canonical literal rendering, or 'min'/'min+1'/'max'.")
    private String name;
    /**
     * The cardinality this point selects, for 'cardinality' facets.
     * 
     */
    @JsonProperty("size")
    @JsonPropertyDescription("The cardinality this point selects, for 'cardinality' facets.")
    private Long size;
    /**
     * The literal this point selects, for 'value' facets.
     * 
     */
    @JsonProperty("value")
    @JsonPropertyDescription("The literal this point selects, for 'value' facets.")
    private Object value;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Stable within the dimension: 'present'/'absent', 'null'/'non-null', an alternative name, a canonical literal rendering, or 'min'/'min+1'/'max'.
     * (Required)
     * 
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * Stable within the dimension: 'present'/'absent', 'null'/'non-null', an alternative name, a canonical literal rendering, or 'min'/'min+1'/'max'.
     * (Required)
     * 
     */
    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * The cardinality this point selects, for 'cardinality' facets.
     * 
     */
    @JsonProperty("size")
    public Long getSize() {
        return size;
    }

    /**
     * The cardinality this point selects, for 'cardinality' facets.
     * 
     */
    @JsonProperty("size")
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * The literal this point selects, for 'value' facets.
     * 
     */
    @JsonProperty("value")
    public Object getValue() {
        return value;
    }

    /**
     * The literal this point selects, for 'value' facets.
     * 
     */
    @JsonProperty("value")
    public void setValue(Object value) {
        this.value = value;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Point.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("name");
        sb.append('=');
        sb.append(((this.name == null)?"<null>":this.name));
        sb.append(',');
        sb.append("size");
        sb.append('=');
        sb.append(((this.size == null)?"<null>":this.size));
        sb.append(',');
        sb.append("value");
        sb.append('=');
        sb.append(((this.value == null)?"<null>":this.value));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.name == null)? 0 :this.name.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.size == null)? 0 :this.size.hashCode()));
        result = ((result* 31)+((this.value == null)? 0 :this.value.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Point) == false) {
            return false;
        }
        Point rhs = ((Point) other);
        return (((((this.name == rhs.name)||((this.name!= null)&&this.name.equals(rhs.name)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.size == rhs.size)||((this.size!= null)&&this.size.equals(rhs.size))))&&((this.value == rhs.value)||((this.value!= null)&&this.value.equals(rhs.value))));
    }

}
