/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */

package io.pact.janus.bindings.shape.v1;

import java.util.List;

/**
 * Known values of this package's open vocabularies. Values not listed here may appear and
 * must be handled by policy, never rejected (engine-protocol spec §2.2 rule 3).
 */
public final class Vocabulary {
  private Vocabulary() {}

  /** Known values of {@code Dimension.facet}. */
  public static final class DimensionFacet {
    private DimensionFacet() {}

    public static final String PRESENCE = "presence";
    public static final String NULLABILITY = "nullability";
    public static final String VALUE = "value";
    public static final String ALTERNATIVE = "alternative";
    public static final String CARDINALITY = "cardinality";

    public static final List<String> KNOWN = List.of(PRESENCE, NULLABILITY, VALUE, ALTERNATIVE, CARDINALITY);
  }

  /** Known values of {@code Shape.encoded}. */
  public static final class ShapeEncoded {
    private ShapeEncoded() {}

    public static final String BASE64 = "base64";

    public static final List<String> KNOWN = List.of(BASE64);
  }

  /** Known values of {@code Shape.shape}. */
  public static final class ShapeShape {
    private ShapeShape() {}

    public static final String ANY = "any";
    public static final String EQUALITY = "equality";
    public static final String TYPE = "type";
    public static final String STRING = "string";
    public static final String NUMBER = "number";
    public static final String INTEGER = "integer";
    public static final String DECIMAL = "decimal";
    public static final String BOOLEAN = "boolean";
    public static final String NULL = "null";
    public static final String REGEX = "regex";
    public static final String DATETIME = "datetime";
    public static final String DATE = "date";
    public static final String TIME = "time";
    public static final String INCLUDE = "include";
    public static final String CONTENT_TYPE = "content-type";
    public static final String SEMVER = "semver";
    public static final String NOT_EMPTY = "not-empty";
    public static final String OBJECT = "object";
    public static final String ARRAY = "array";
    public static final String EACH_LIKE = "each-like";
    public static final String EACH_ENTRY = "each-entry";
    public static final String CONTAINS = "contains";
    public static final String OPTIONAL = "optional";
    public static final String NULLABLE = "nullable";
    public static final String FORBIDDEN = "forbidden";
    public static final String ANY_OF = "any-of";
    public static final String ONE_OF = "one-of";

    public static final List<String> KNOWN = List.of(ANY, EQUALITY, TYPE, STRING, NUMBER, INTEGER, DECIMAL, BOOLEAN, NULL, REGEX, DATETIME, DATE, TIME, INCLUDE, CONTENT_TYPE, SEMVER, NOT_EMPTY, OBJECT, ARRAY, EACH_LIKE, EACH_ENTRY, CONTAINS, OPTIONAL, NULLABLE, FORBIDDEN, ANY_OF, ONE_OF);
  }
}
