// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pact {
        pub mod gauntlet {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod events {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ErrorCode {
                    InvalidSpec,
                    UnsupportedSpecVersion,
                    SessionNotFound,
                    Internal,
                    ComponentUnavailable,
                }
                impl ::core::fmt::Debug for ErrorCode {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ErrorCode::InvalidSpec => {
                                f.debug_tuple("ErrorCode::InvalidSpec").finish()
                            }
                            ErrorCode::UnsupportedSpecVersion => {
                                f.debug_tuple("ErrorCode::UnsupportedSpecVersion").finish()
                            }
                            ErrorCode::SessionNotFound => {
                                f.debug_tuple("ErrorCode::SessionNotFound").finish()
                            }
                            ErrorCode::Internal => {
                                f.debug_tuple("ErrorCode::Internal").finish()
                            }
                            ErrorCode::ComponentUnavailable => {
                                f.debug_tuple("ErrorCode::ComponentUnavailable").finish()
                            }
                        }
                    }
                }
                impl ErrorCode {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ErrorCode {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => ErrorCode::InvalidSpec,
                            1 => ErrorCode::UnsupportedSpecVersion,
                            2 => ErrorCode::SessionNotFound,
                            3 => ErrorCode::Internal,
                            4 => ErrorCode::ComponentUnavailable,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Clone)]
                pub enum VerifyEvent {
                    Started(_rt::String),
                    InteractionResult(_rt::String),
                    Finished(_rt::String),
                    HookInvoked(_rt::String),
                }
                impl ::core::fmt::Debug for VerifyEvent {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            VerifyEvent::Started(e) => {
                                f.debug_tuple("VerifyEvent::Started").field(e).finish()
                            }
                            VerifyEvent::InteractionResult(e) => {
                                f.debug_tuple("VerifyEvent::InteractionResult")
                                    .field(e)
                                    .finish()
                            }
                            VerifyEvent::Finished(e) => {
                                f.debug_tuple("VerifyEvent::Finished").field(e).finish()
                            }
                            VerifyEvent::HookInvoked(e) => {
                                f.debug_tuple("VerifyEvent::HookInvoked").field(e).finish()
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_next_event_cabi<T: Guest>(arg0: i32) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::next_event(arg0 as u32);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Some(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                VerifyEvent::Started(e) => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec2 = (e.into_bytes()).into_boxed_slice();
                                    let ptr2 = vec2.as_ptr().cast::<u8>();
                                    let len2 = vec2.len();
                                    ::core::mem::forget(vec2);
                                    *ptr1
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len2;
                                    *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr2.cast_mut();
                                }
                                VerifyEvent::InteractionResult(e) => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec3 = (e.into_bytes()).into_boxed_slice();
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    ::core::mem::forget(vec3);
                                    *ptr1
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr3.cast_mut();
                                }
                                VerifyEvent::Finished(e) => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec4 = (e.into_bytes()).into_boxed_slice();
                                    let ptr4 = vec4.as_ptr().cast::<u8>();
                                    let len4 = vec4.len();
                                    ::core::mem::forget(vec4);
                                    *ptr1
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len4;
                                    *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr4.cast_mut();
                                }
                                VerifyEvent::HookInvoked(e) => {
                                    *ptr1
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (3i32) as u8;
                                    let vec5 = (e.into_bytes()).into_boxed_slice();
                                    let ptr5 = vec5.as_ptr().cast::<u8>();
                                    let len5 = vec5.len();
                                    ::core::mem::forget(vec5);
                                    *ptr1
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len5;
                                    *ptr1
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr5.cast_mut();
                                }
                            }
                        }
                        None => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_next_event<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                                1 => {
                                    let l4 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                }
                                2 => {
                                    let l6 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l6, l7, 1);
                                }
                                _ => {
                                    let l8 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l9 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l8, l9, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_last_error_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::last_error();
                    result0.clone() as i32
                }
                pub trait Guest {
                    fn next_event(seq: u32) -> Option<VerifyEvent>;
                    fn last_error() -> ErrorCode;
                }
                #[doc(hidden)]
                macro_rules! __export_pact_gauntlet_events_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pact:gauntlet/events@0.1.0#next-event")] unsafe extern "C" fn
                        export_next_event(arg0 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_next_event_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "cabi_post_pact:gauntlet/events@0.1.0#next-event")] unsafe extern
                        "C" fn _post_return_next_event(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_next_event::<$ty > (arg0) } }
                        #[unsafe (export_name = "pact:gauntlet/events@0.1.0#last-error")]
                        unsafe extern "C" fn export_last_error() -> i32 { unsafe {
                        $($path_to_types)*:: _export_last_error_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pact_gauntlet_events_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pact::gauntlet::events::__export_pact_gauntlet_events_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::pact::gauntlet::events);
    };
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pact:gauntlet@0.1.0:plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 432] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x02\x01A\x02\x01\
A\x02\x01B\x09\x01m\x05\x0cinvalid-spec\x18unsupported-spec-version\x11session-n\
ot-found\x08internal\x15component-unavailable\x04\0\x0aerror-code\x03\0\0\x01q\x04\
\x07started\x01s\0\x12interaction-result\x01s\0\x08finished\x01s\0\x0chook-invok\
ed\x01s\0\x04\0\x0cverify-event\x03\0\x02\x01k\x03\x01@\x01\x03seqy\0\x04\x04\0\x0a\
next-event\x01\x05\x01@\0\0\x01\x04\0\x0alast-error\x01\x06\x04\0\x1apact:gauntl\
et/events@0.1.0\x05\0\x04\0\x1apact:gauntlet/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06\
plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227\
.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
