/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AddInteractionResult
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "handle"
})
public class AddInteractionResult {

    /**
     * Identifies the interaction within this session; invalid after finalise.
     * (Required)
     * 
     */
    @JsonProperty("handle")
    @JsonPropertyDescription("Identifies the interaction within this session; invalid after finalise.")
    private String handle;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Identifies the interaction within this session; invalid after finalise.
     * (Required)
     * 
     */
    @JsonProperty("handle")
    public String getHandle() {
        return handle;
    }

    /**
     * Identifies the interaction within this session; invalid after finalise.
     * (Required)
     * 
     */
    @JsonProperty("handle")
    public void setHandle(String handle) {
        this.handle = handle;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(AddInteractionResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("handle");
        sb.append('=');
        sb.append(((this.handle == null)?"<null>":this.handle));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.handle == null)? 0 :this.handle.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof AddInteractionResult) == false) {
            return false;
        }
        AddInteractionResult rhs = ((AddInteractionResult) other);
        return (((this.handle == rhs.handle)||((this.handle!= null)&&this.handle.equals(rhs.handle)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
