/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CheckResult
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "format",
    "report"
})
public class CheckResult {

    /**
     * How the consumer document identified itself: 'janus-contract/1', or 'pact/<version>' for a v1-v4 pact converted on the way in.
     * (Required)
     * 
     */
    @JsonProperty("format")
    @JsonPropertyDescription("How the consumer document identified itself: 'janus-contract/1', or 'pact/<version>' for a v1-v4 pact converted on the way in.")
    private java.lang.String format;
    /**
     * The subsumption report (design 2.8 §6, 'janus-subsumption-report/1'). Every interaction of the contract appears in it, including the ones the provider published nothing for.
     * (Required)
     * 
     */
    @JsonProperty("report")
    @JsonPropertyDescription("The subsumption report (design 2.8 \u00a76, 'janus-subsumption-report/1'). Every interaction of the contract appears in it, including the ones the provider published nothing for.")
    private Map<String, Object> report;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * How the consumer document identified itself: 'janus-contract/1', or 'pact/<version>' for a v1-v4 pact converted on the way in.
     * (Required)
     * 
     */
    @JsonProperty("format")
    public java.lang.String getFormat() {
        return format;
    }

    /**
     * How the consumer document identified itself: 'janus-contract/1', or 'pact/<version>' for a v1-v4 pact converted on the way in.
     * (Required)
     * 
     */
    @JsonProperty("format")
    public void setFormat(java.lang.String format) {
        this.format = format;
    }

    /**
     * The subsumption report (design 2.8 §6, 'janus-subsumption-report/1'). Every interaction of the contract appears in it, including the ones the provider published nothing for.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public Map<String, Object> getReport() {
        return report;
    }

    /**
     * The subsumption report (design 2.8 §6, 'janus-subsumption-report/1'). Every interaction of the contract appears in it, including the ones the provider published nothing for.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public void setReport(Map<String, Object> report) {
        this.report = report;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(CheckResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("format");
        sb.append('=');
        sb.append(((this.format == null)?"<null>":this.format));
        sb.append(',');
        sb.append("report");
        sb.append('=');
        sb.append(((this.report == null)?"<null>":this.report));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.format == null)? 0 :this.format.hashCode()));
        result = ((result* 31)+((this.report == null)? 0 :this.report.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof CheckResult) == false) {
            return false;
        }
        CheckResult rhs = ((CheckResult) other);
        return ((((this.format == rhs.format)||((this.format!= null)&&this.format.equals(rhs.format)))&&((this.report == rhs.report)||((this.report!= null)&&this.report.equals(rhs.report))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
