/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CompatibilitySummary
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "blocked",
    "exempt",
    "findings",
    "pairs",
    "passed",
    "reviews",
    "warned"
})
public class CompatibilitySummary {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("blocked")
    private Long blocked;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    private Long exempt;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    private Long findings;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    private Long pairs;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("passed")
    private Long passed;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    private Long reviews;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("warned")
    private Long warned;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("blocked")
    public Long getBlocked() {
        return blocked;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("blocked")
    public void setBlocked(Long blocked) {
        this.blocked = blocked;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    public Long getExempt() {
        return exempt;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    public void setExempt(Long exempt) {
        this.exempt = exempt;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public Long getFindings() {
        return findings;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public void setFindings(Long findings) {
        this.findings = findings;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    public Long getPairs() {
        return pairs;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    public void setPairs(Long pairs) {
        this.pairs = pairs;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("passed")
    public Long getPassed() {
        return passed;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("passed")
    public void setPassed(Long passed) {
        this.passed = passed;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    public Long getReviews() {
        return reviews;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    public void setReviews(Long reviews) {
        this.reviews = reviews;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("warned")
    public Long getWarned() {
        return warned;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("warned")
    public void setWarned(Long warned) {
        this.warned = warned;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(CompatibilitySummary.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("blocked");
        sb.append('=');
        sb.append(((this.blocked == null)?"<null>":this.blocked));
        sb.append(',');
        sb.append("exempt");
        sb.append('=');
        sb.append(((this.exempt == null)?"<null>":this.exempt));
        sb.append(',');
        sb.append("findings");
        sb.append('=');
        sb.append(((this.findings == null)?"<null>":this.findings));
        sb.append(',');
        sb.append("pairs");
        sb.append('=');
        sb.append(((this.pairs == null)?"<null>":this.pairs));
        sb.append(',');
        sb.append("passed");
        sb.append('=');
        sb.append(((this.passed == null)?"<null>":this.passed));
        sb.append(',');
        sb.append("reviews");
        sb.append('=');
        sb.append(((this.reviews == null)?"<null>":this.reviews));
        sb.append(',');
        sb.append("warned");
        sb.append('=');
        sb.append(((this.warned == null)?"<null>":this.warned));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.blocked == null)? 0 :this.blocked.hashCode()));
        result = ((result* 31)+((this.reviews == null)? 0 :this.reviews.hashCode()));
        result = ((result* 31)+((this.findings == null)? 0 :this.findings.hashCode()));
        result = ((result* 31)+((this.warned == null)? 0 :this.warned.hashCode()));
        result = ((result* 31)+((this.exempt == null)? 0 :this.exempt.hashCode()));
        result = ((result* 31)+((this.passed == null)? 0 :this.passed.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.pairs == null)? 0 :this.pairs.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof CompatibilitySummary) == false) {
            return false;
        }
        CompatibilitySummary rhs = ((CompatibilitySummary) other);
        return (((((((((this.blocked == rhs.blocked)||((this.blocked!= null)&&this.blocked.equals(rhs.blocked)))&&((this.reviews == rhs.reviews)||((this.reviews!= null)&&this.reviews.equals(rhs.reviews))))&&((this.findings == rhs.findings)||((this.findings!= null)&&this.findings.equals(rhs.findings))))&&((this.warned == rhs.warned)||((this.warned!= null)&&this.warned.equals(rhs.warned))))&&((this.exempt == rhs.exempt)||((this.exempt!= null)&&this.exempt.equals(rhs.exempt))))&&((this.passed == rhs.passed)||((this.passed!= null)&&this.passed.equals(rhs.passed))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.pairs == rhs.pairs)||((this.pairs!= null)&&this.pairs.equals(rhs.pairs))));
    }

}
