/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CompatibilityReport
 * <p>
 * The can-i-deploy answer for one run (spec.md §8.6): every pair asked about, why each decided the way it did, and what policy decided it. Owned by plan task 7.4 — design 2.8 §1 lists combining its report with verification results as out of its own scope.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "$format",
    "as-of",
    "decision",
    "pairs",
    "policy",
    "summary"
})
public class CompatibilityReport {

    /**
     * 'janus-compatibility-report/1'.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    @JsonPropertyDescription("'janus-compatibility-report/1'.")
    private String $format;
    /**
     * The date exemption expiry was judged against, when the host supplied one.
     * 
     */
    @JsonProperty("as-of")
    @JsonPropertyDescription("The date exemption expiry was judged against, when the host supplied one.")
    private String asOf;
    /**
     * Decision
     * <p>
     * 'pass' nothing to say, 'warn' something to read that does not stop the deploy, 'block' stop. Open vocabulary, ordered as written: a host that does not know a value treats it as at least as severe as 'warn'.
     * (Required)
     * 
     */
    @JsonProperty("decision")
    @JsonPropertyDescription("'pass' nothing to say, 'warn' something to read that does not stop the deploy, 'block' stop. Open vocabulary, ordered as written: a host that does not know a value treats it as at least as severe as 'warn'.")
    private String decision;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    private List<PairResult> pairs;
    /**
     * PolicyView
     * <p>
     * The policy this run resolved to, recorded because design 2.8 §7.1's layering means the answer is in no single file.
     * (Required)
     * 
     */
    @JsonProperty("policy")
    @JsonPropertyDescription("The policy this run resolved to, recorded because design 2.8 \u00a77.1's layering means the answer is in no single file.")
    private PolicyView policy;
    /**
     * CompatibilitySummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("summary")
    private CompatibilitySummary summary;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 'janus-compatibility-report/1'.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    public String get$format() {
        return $format;
    }

    /**
     * 'janus-compatibility-report/1'.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    public void set$format(String $format) {
        this.$format = $format;
    }

    /**
     * The date exemption expiry was judged against, when the host supplied one.
     * 
     */
    @JsonProperty("as-of")
    public String getAsOf() {
        return asOf;
    }

    /**
     * The date exemption expiry was judged against, when the host supplied one.
     * 
     */
    @JsonProperty("as-of")
    public void setAsOf(String asOf) {
        this.asOf = asOf;
    }

    /**
     * Decision
     * <p>
     * 'pass' nothing to say, 'warn' something to read that does not stop the deploy, 'block' stop. Open vocabulary, ordered as written: a host that does not know a value treats it as at least as severe as 'warn'.
     * (Required)
     * 
     */
    @JsonProperty("decision")
    public String getDecision() {
        return decision;
    }

    /**
     * Decision
     * <p>
     * 'pass' nothing to say, 'warn' something to read that does not stop the deploy, 'block' stop. Open vocabulary, ordered as written: a host that does not know a value treats it as at least as severe as 'warn'.
     * (Required)
     * 
     */
    @JsonProperty("decision")
    public void setDecision(String decision) {
        this.decision = decision;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    public List<PairResult> getPairs() {
        return pairs;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("pairs")
    public void setPairs(List<PairResult> pairs) {
        this.pairs = pairs;
    }

    /**
     * PolicyView
     * <p>
     * The policy this run resolved to, recorded because design 2.8 §7.1's layering means the answer is in no single file.
     * (Required)
     * 
     */
    @JsonProperty("policy")
    public PolicyView getPolicy() {
        return policy;
    }

    /**
     * PolicyView
     * <p>
     * The policy this run resolved to, recorded because design 2.8 §7.1's layering means the answer is in no single file.
     * (Required)
     * 
     */
    @JsonProperty("policy")
    public void setPolicy(PolicyView policy) {
        this.policy = policy;
    }

    /**
     * CompatibilitySummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("summary")
    public CompatibilitySummary getSummary() {
        return summary;
    }

    /**
     * CompatibilitySummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("summary")
    public void setSummary(CompatibilitySummary summary) {
        this.summary = summary;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(CompatibilityReport.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("$format");
        sb.append('=');
        sb.append(((this.$format == null)?"<null>":this.$format));
        sb.append(',');
        sb.append("asOf");
        sb.append('=');
        sb.append(((this.asOf == null)?"<null>":this.asOf));
        sb.append(',');
        sb.append("decision");
        sb.append('=');
        sb.append(((this.decision == null)?"<null>":this.decision));
        sb.append(',');
        sb.append("pairs");
        sb.append('=');
        sb.append(((this.pairs == null)?"<null>":this.pairs));
        sb.append(',');
        sb.append("policy");
        sb.append('=');
        sb.append(((this.policy == null)?"<null>":this.policy));
        sb.append(',');
        sb.append("summary");
        sb.append('=');
        sb.append(((this.summary == null)?"<null>":this.summary));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.summary == null)? 0 :this.summary.hashCode()));
        result = ((result* 31)+((this.asOf == null)? 0 :this.asOf.hashCode()));
        result = ((result* 31)+((this.decision == null)? 0 :this.decision.hashCode()));
        result = ((result* 31)+((this.$format == null)? 0 :this.$format.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.pairs == null)? 0 :this.pairs.hashCode()));
        result = ((result* 31)+((this.policy == null)? 0 :this.policy.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof CompatibilityReport) == false) {
            return false;
        }
        CompatibilityReport rhs = ((CompatibilityReport) other);
        return ((((((((this.summary == rhs.summary)||((this.summary!= null)&&this.summary.equals(rhs.summary)))&&((this.asOf == rhs.asOf)||((this.asOf!= null)&&this.asOf.equals(rhs.asOf))))&&((this.decision == rhs.decision)||((this.decision!= null)&&this.decision.equals(rhs.decision))))&&((this.$format == rhs.$format)||((this.$format!= null)&&this.$format.equals(rhs.$format))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.pairs == rhs.pairs)||((this.pairs!= null)&&this.pairs.equals(rhs.pairs))))&&((this.policy == rhs.policy)||((this.policy!= null)&&this.policy.equals(rhs.policy))));
    }

}
