/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DecideResult
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "report",
    "text"
})
public class DecideResult {

    /**
     * CompatibilityReport
     * <p>
     * The can-i-deploy answer for one run (spec.md §8.6): every pair asked about, why each decided the way it did, and what policy decided it. Owned by plan task 7.4 — design 2.8 §1 lists combining its report with verification results as out of its own scope.
     * (Required)
     * 
     */
    @JsonProperty("report")
    @JsonPropertyDescription("The can-i-deploy answer for one run (spec.md \u00a78.6): every pair asked about, why each decided the way it did, and what policy decided it. Owned by plan task 7.4 \u2014 design 2.8 \u00a71 lists combining its report with verification results as out of its own scope.")
    private CompatibilityReport report;
    /**
     * The page a person reads: design 2.8 §6.4's finding block per pair, under a decision. Rendered by the engine so that two hosts printing the same decision print the same words.
     * (Required)
     * 
     */
    @JsonProperty("text")
    @JsonPropertyDescription("The page a person reads: design 2.8 \u00a76.4's finding block per pair, under a decision. Rendered by the engine so that two hosts printing the same decision print the same words.")
    private String text;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * CompatibilityReport
     * <p>
     * The can-i-deploy answer for one run (spec.md §8.6): every pair asked about, why each decided the way it did, and what policy decided it. Owned by plan task 7.4 — design 2.8 §1 lists combining its report with verification results as out of its own scope.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public CompatibilityReport getReport() {
        return report;
    }

    /**
     * CompatibilityReport
     * <p>
     * The can-i-deploy answer for one run (spec.md §8.6): every pair asked about, why each decided the way it did, and what policy decided it. Owned by plan task 7.4 — design 2.8 §1 lists combining its report with verification results as out of its own scope.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public void setReport(CompatibilityReport report) {
        this.report = report;
    }

    /**
     * The page a person reads: design 2.8 §6.4's finding block per pair, under a decision. Rendered by the engine so that two hosts printing the same decision print the same words.
     * (Required)
     * 
     */
    @JsonProperty("text")
    public String getText() {
        return text;
    }

    /**
     * The page a person reads: design 2.8 §6.4's finding block per pair, under a decision. Rendered by the engine so that two hosts printing the same decision print the same words.
     * (Required)
     * 
     */
    @JsonProperty("text")
    public void setText(String text) {
        this.text = text;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(DecideResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("report");
        sb.append('=');
        sb.append(((this.report == null)?"<null>":this.report));
        sb.append(',');
        sb.append("text");
        sb.append('=');
        sb.append(((this.text == null)?"<null>":this.text));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.report == null)? 0 :this.report.hashCode()));
        result = ((result* 31)+((this.text == null)? 0 :this.text.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof DecideResult) == false) {
            return false;
        }
        DecideResult rhs = ((DecideResult) other);
        return ((((this.report == rhs.report)||((this.report!= null)&&this.report.equals(rhs.report)))&&((this.text == rhs.text)||((this.text!= null)&&this.text.equals(rhs.text))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
