/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DecidePair
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "consumer",
    "format",
    "provider",
    "subsumption"
})
public class DecidePair {

    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    private Party consumer;
    /**
     * How the consumer document identified itself, as CheckResult reported it.
     * 
     */
    @JsonProperty("format")
    @JsonPropertyDescription("How the consumer document identified itself, as CheckResult reported it.")
    private java.lang.String format;
    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("provider")
    private Party provider;
    /**
     * This pair's subsumption report, when the host has one. Its absence is not an error: a provider that has published no shape gets replay-only semantics (design 2.8 §6.3), which is what makes the check adoptable per provider.
     * 
     */
    @JsonProperty("subsumption")
    @JsonPropertyDescription("This pair's subsumption report, when the host has one. Its absence is not an error: a provider that has published no shape gets replay-only semantics (design 2.8 \u00a76.3), which is what makes the check adoptable per provider.")
    private Map<String, Object> subsumption;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    public Party getConsumer() {
        return consumer;
    }

    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    public void setConsumer(Party consumer) {
        this.consumer = consumer;
    }

    /**
     * How the consumer document identified itself, as CheckResult reported it.
     * 
     */
    @JsonProperty("format")
    public java.lang.String getFormat() {
        return format;
    }

    /**
     * How the consumer document identified itself, as CheckResult reported it.
     * 
     */
    @JsonProperty("format")
    public void setFormat(java.lang.String format) {
        this.format = format;
    }

    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("provider")
    public Party getProvider() {
        return provider;
    }

    /**
     * Party
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("provider")
    public void setProvider(Party provider) {
        this.provider = provider;
    }

    /**
     * This pair's subsumption report, when the host has one. Its absence is not an error: a provider that has published no shape gets replay-only semantics (design 2.8 §6.3), which is what makes the check adoptable per provider.
     * 
     */
    @JsonProperty("subsumption")
    public Map<String, Object> getSubsumption() {
        return subsumption;
    }

    /**
     * This pair's subsumption report, when the host has one. Its absence is not an error: a provider that has published no shape gets replay-only semantics (design 2.8 §6.3), which is what makes the check adoptable per provider.
     * 
     */
    @JsonProperty("subsumption")
    public void setSubsumption(Map<String, Object> subsumption) {
        this.subsumption = subsumption;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(DecidePair.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("consumer");
        sb.append('=');
        sb.append(((this.consumer == null)?"<null>":this.consumer));
        sb.append(',');
        sb.append("format");
        sb.append('=');
        sb.append(((this.format == null)?"<null>":this.format));
        sb.append(',');
        sb.append("provider");
        sb.append('=');
        sb.append(((this.provider == null)?"<null>":this.provider));
        sb.append(',');
        sb.append("subsumption");
        sb.append('=');
        sb.append(((this.subsumption == null)?"<null>":this.subsumption));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.format == null)? 0 :this.format.hashCode()));
        result = ((result* 31)+((this.subsumption == null)? 0 :this.subsumption.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.provider == null)? 0 :this.provider.hashCode()));
        result = ((result* 31)+((this.consumer == null)? 0 :this.consumer.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof DecidePair) == false) {
            return false;
        }
        DecidePair rhs = ((DecidePair) other);
        return ((((((this.format == rhs.format)||((this.format!= null)&&this.format.equals(rhs.format)))&&((this.subsumption == rhs.subsumption)||((this.subsumption!= null)&&this.subsumption.equals(rhs.subsumption))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.provider == rhs.provider)||((this.provider!= null)&&this.provider.equals(rhs.provider))))&&((this.consumer == rhs.consumer)||((this.consumer!= null)&&this.consumer.equals(rhs.consumer))));
    }

}
