/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EncodingCapability
 * <p>
 * Frame encoding negotiation (spec.md §3.4). The host sends 'accepts' in preference order; the engine answers with 'selected'. Absent on either side means json. The hello exchange itself is always JSON, and JSON is mandatory for both parties, so negotiation cannot fail.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "accepts",
    "selected"
})
public class EncodingCapability {

    /**
     * Encodings the host accepts, most preferred first.
     * 
     */
    @JsonProperty("accepts")
    @JsonPropertyDescription("Encodings the host accepts, most preferred first.")
    private List<String> accepts;
    /**
     * EncodingName
     * <p>
     * How a frame is written on the wire, as distinct from the document it encodes. Open vocabulary; v1 defines only 'json' (UTF-8, the mandatory baseline). A new encoding is an additive change (spec.md §11.2) and never bumps the protocol version.
     * 
     */
    @JsonProperty("selected")
    @JsonPropertyDescription("How a frame is written on the wire, as distinct from the document it encodes. Open vocabulary; v1 defines only 'json' (UTF-8, the mandatory baseline). A new encoding is an additive change (spec.md \u00a711.2) and never bumps the protocol version.")
    private String selected;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Encodings the host accepts, most preferred first.
     * 
     */
    @JsonProperty("accepts")
    public List<String> getAccepts() {
        return accepts;
    }

    /**
     * Encodings the host accepts, most preferred first.
     * 
     */
    @JsonProperty("accepts")
    public void setAccepts(List<String> accepts) {
        this.accepts = accepts;
    }

    /**
     * EncodingName
     * <p>
     * How a frame is written on the wire, as distinct from the document it encodes. Open vocabulary; v1 defines only 'json' (UTF-8, the mandatory baseline). A new encoding is an additive change (spec.md §11.2) and never bumps the protocol version.
     * 
     */
    @JsonProperty("selected")
    public String getSelected() {
        return selected;
    }

    /**
     * EncodingName
     * <p>
     * How a frame is written on the wire, as distinct from the document it encodes. Open vocabulary; v1 defines only 'json' (UTF-8, the mandatory baseline). A new encoding is an additive change (spec.md §11.2) and never bumps the protocol version.
     * 
     */
    @JsonProperty("selected")
    public void setSelected(String selected) {
        this.selected = selected;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(EncodingCapability.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("accepts");
        sb.append('=');
        sb.append(((this.accepts == null)?"<null>":this.accepts));
        sb.append(',');
        sb.append("selected");
        sb.append('=');
        sb.append(((this.selected == null)?"<null>":this.selected));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.accepts == null)? 0 :this.accepts.hashCode()));
        result = ((result* 31)+((this.selected == null)? 0 :this.selected.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof EncodingCapability) == false) {
            return false;
        }
        EncodingCapability rhs = ((EncodingCapability) other);
        return ((((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties)))&&((this.accepts == rhs.accepts)||((this.accepts!= null)&&this.accepts.equals(rhs.accepts))))&&((this.selected == rhs.selected)||((this.selected!= null)&&this.selected.equals(rhs.selected))));
    }

}
