/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EngineError
 * <p>
 * The structured error value carried in a ResponseFrame's 'error' member. Errors are values: this is the only way an operation fails. Taxonomy and details conventions in spec.md §10.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "category",
    "code",
    "details",
    "message"
})
public class EngineError {

    /**
     * Coarse classification enabling handling of unknown codes. Absent or unknown is treated as 'internal'.
     * 
     */
    @JsonProperty("category")
    @JsonPropertyDescription("Coarse classification enabling handling of unknown codes. Absent or unknown is treated as 'internal'.")
    private java.lang.String category;
    /**
     * Machine-readable error code. Open vocabulary; unknown codes are handled by the category fallback (spec.md §10.2).
     * (Required)
     * 
     */
    @JsonProperty("code")
    @JsonPropertyDescription("Machine-readable error code. Open vocabulary; unknown codes are handled by the category fallback (spec.md \u00a710.2).")
    private java.lang.String code;
    /**
     * Code-specific structure per spec.md §10.2 — e.g. 'supported' (protocol-version-unsupported), 'op' (operation-unsupported), 'problems: [{path, message}]' (interaction-invalid/contract-invalid), 'component' and opaque 'error' (component-*).
     * 
     */
    @JsonProperty("details")
    @JsonPropertyDescription("Code-specific structure per spec.md \u00a710.2 \u2014 e.g. 'supported' (protocol-version-unsupported), 'op' (operation-unsupported), 'problems: [{path, message}]' (interaction-invalid/contract-invalid), 'component' and opaque 'error' (component-*).")
    private Map<String, Object> details;
    /**
     * Human-readable description, not intended for programmatic dispatch.
     * (Required)
     * 
     */
    @JsonProperty("message")
    @JsonPropertyDescription("Human-readable description, not intended for programmatic dispatch.")
    private java.lang.String message;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Coarse classification enabling handling of unknown codes. Absent or unknown is treated as 'internal'.
     * 
     */
    @JsonProperty("category")
    public java.lang.String getCategory() {
        return category;
    }

    /**
     * Coarse classification enabling handling of unknown codes. Absent or unknown is treated as 'internal'.
     * 
     */
    @JsonProperty("category")
    public void setCategory(java.lang.String category) {
        this.category = category;
    }

    /**
     * Machine-readable error code. Open vocabulary; unknown codes are handled by the category fallback (spec.md §10.2).
     * (Required)
     * 
     */
    @JsonProperty("code")
    public java.lang.String getCode() {
        return code;
    }

    /**
     * Machine-readable error code. Open vocabulary; unknown codes are handled by the category fallback (spec.md §10.2).
     * (Required)
     * 
     */
    @JsonProperty("code")
    public void setCode(java.lang.String code) {
        this.code = code;
    }

    /**
     * Code-specific structure per spec.md §10.2 — e.g. 'supported' (protocol-version-unsupported), 'op' (operation-unsupported), 'problems: [{path, message}]' (interaction-invalid/contract-invalid), 'component' and opaque 'error' (component-*).
     * 
     */
    @JsonProperty("details")
    public Map<String, Object> getDetails() {
        return details;
    }

    /**
     * Code-specific structure per spec.md §10.2 — e.g. 'supported' (protocol-version-unsupported), 'op' (operation-unsupported), 'problems: [{path, message}]' (interaction-invalid/contract-invalid), 'component' and opaque 'error' (component-*).
     * 
     */
    @JsonProperty("details")
    public void setDetails(Map<String, Object> details) {
        this.details = details;
    }

    /**
     * Human-readable description, not intended for programmatic dispatch.
     * (Required)
     * 
     */
    @JsonProperty("message")
    public java.lang.String getMessage() {
        return message;
    }

    /**
     * Human-readable description, not intended for programmatic dispatch.
     * (Required)
     * 
     */
    @JsonProperty("message")
    public void setMessage(java.lang.String message) {
        this.message = message;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(EngineError.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("category");
        sb.append('=');
        sb.append(((this.category == null)?"<null>":this.category));
        sb.append(',');
        sb.append("code");
        sb.append('=');
        sb.append(((this.code == null)?"<null>":this.code));
        sb.append(',');
        sb.append("details");
        sb.append('=');
        sb.append(((this.details == null)?"<null>":this.details));
        sb.append(',');
        sb.append("message");
        sb.append('=');
        sb.append(((this.message == null)?"<null>":this.message));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.details == null)? 0 :this.details.hashCode()));
        result = ((result* 31)+((this.code == null)? 0 :this.code.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.category == null)? 0 :this.category.hashCode()));
        result = ((result* 31)+((this.message == null)? 0 :this.message.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof EngineError) == false) {
            return false;
        }
        EngineError rhs = ((EngineError) other);
        return ((((((this.details == rhs.details)||((this.details!= null)&&this.details.equals(rhs.details)))&&((this.code == rhs.code)||((this.code!= null)&&this.code.equals(rhs.code))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.category == rhs.category)||((this.category!= null)&&this.category.equals(rhs.category))))&&((this.message == rhs.message)||((this.message!= null)&&this.message.equals(rhs.message))));
    }

}
