/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Event
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "kind",
    "last",
    "payload",
    "seq",
    "stream"
})
public class Event {

    /**
     * Open vocabulary, namespaced like operations. Unknown kinds are handled by policy, never by failure; seq and last are honoured regardless.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    @JsonPropertyDescription("Open vocabulary, namespaced like operations. Unknown kinds are handled by policy, never by failure; seq and last are honoured regardless.")
    private java.lang.String kind;
    /**
     * Structural termination: true on the final event of a stream, whatever its kind.
     * 
     */
    @JsonProperty("last")
    @JsonPropertyDescription("Structural termination: true on the final event of a stream, whatever its kind.")
    private Boolean last;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("payload")
    private Map<String, Object> payload;
    /**
     * Per-stream, starts at 1, increments by 1, no gaps.
     * (Required)
     * 
     */
    @JsonProperty("seq")
    @JsonPropertyDescription("Per-stream, starts at 1, increments by 1, no gaps.")
    private Long seq;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("stream")
    private java.lang.String stream;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Open vocabulary, namespaced like operations. Unknown kinds are handled by policy, never by failure; seq and last are honoured regardless.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public java.lang.String getKind() {
        return kind;
    }

    /**
     * Open vocabulary, namespaced like operations. Unknown kinds are handled by policy, never by failure; seq and last are honoured regardless.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public void setKind(java.lang.String kind) {
        this.kind = kind;
    }

    /**
     * Structural termination: true on the final event of a stream, whatever its kind.
     * 
     */
    @JsonProperty("last")
    public Boolean getLast() {
        return last;
    }

    /**
     * Structural termination: true on the final event of a stream, whatever its kind.
     * 
     */
    @JsonProperty("last")
    public void setLast(Boolean last) {
        this.last = last;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("payload")
    public Map<String, Object> getPayload() {
        return payload;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("payload")
    public void setPayload(Map<String, Object> payload) {
        this.payload = payload;
    }

    /**
     * Per-stream, starts at 1, increments by 1, no gaps.
     * (Required)
     * 
     */
    @JsonProperty("seq")
    public Long getSeq() {
        return seq;
    }

    /**
     * Per-stream, starts at 1, increments by 1, no gaps.
     * (Required)
     * 
     */
    @JsonProperty("seq")
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("stream")
    public java.lang.String getStream() {
        return stream;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("stream")
    public void setStream(java.lang.String stream) {
        this.stream = stream;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Event.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("kind");
        sb.append('=');
        sb.append(((this.kind == null)?"<null>":this.kind));
        sb.append(',');
        sb.append("last");
        sb.append('=');
        sb.append(((this.last == null)?"<null>":this.last));
        sb.append(',');
        sb.append("payload");
        sb.append('=');
        sb.append(((this.payload == null)?"<null>":this.payload));
        sb.append(',');
        sb.append("seq");
        sb.append('=');
        sb.append(((this.seq == null)?"<null>":this.seq));
        sb.append(',');
        sb.append("stream");
        sb.append('=');
        sb.append(((this.stream == null)?"<null>":this.stream));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.last == null)? 0 :this.last.hashCode()));
        result = ((result* 31)+((this.payload == null)? 0 :this.payload.hashCode()));
        result = ((result* 31)+((this.stream == null)? 0 :this.stream.hashCode()));
        result = ((result* 31)+((this.kind == null)? 0 :this.kind.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.seq == null)? 0 :this.seq.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Event) == false) {
            return false;
        }
        Event rhs = ((Event) other);
        return (((((((this.last == rhs.last)||((this.last!= null)&&this.last.equals(rhs.last)))&&((this.payload == rhs.payload)||((this.payload!= null)&&this.payload.equals(rhs.payload))))&&((this.stream == rhs.stream)||((this.stream!= null)&&this.stream.equals(rhs.stream))))&&((this.kind == rhs.kind)||((this.kind!= null)&&this.kind.equals(rhs.kind))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.seq == rhs.seq)||((this.seq!= null)&&this.seq.equals(rhs.seq))));
    }

}
