/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ExemptionResult
 * <p>
 * One exemption's outcome, echoing the exemption itself (design 2.8 §7.2's selectors) so a reader of the report does not need the policy file open beside it.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "consumer",
    "expires",
    "interaction",
    "matched",
    "path",
    "reason",
    "status"
})
public class ExemptionResult {

    @JsonProperty("consumer")
    private String consumer;
    @JsonProperty("expires")
    private String expires;
    /**
     * InteractionId
     * <p>
     * An interaction by contract spec §4.2's identity: description plus state names.
     * 
     */
    @JsonProperty("interaction")
    @JsonPropertyDescription("An interaction by contract spec \u00a74.2's identity: description plus state names.")
    private InteractionId interaction;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("matched")
    private Long matched;
    @JsonProperty("path")
    private String path;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reason")
    private String reason;
    /**
     * 'applied' silenced at least one finding, 'unused' matched nothing, 'lapsed' is past its own 'expires' date and silenced nothing.
     * (Required)
     * 
     */
    @JsonProperty("status")
    @JsonPropertyDescription("'applied' silenced at least one finding, 'unused' matched nothing, 'lapsed' is past its own 'expires' date and silenced nothing.")
    private String status;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    @JsonProperty("consumer")
    public String getConsumer() {
        return consumer;
    }

    @JsonProperty("consumer")
    public void setConsumer(String consumer) {
        this.consumer = consumer;
    }

    @JsonProperty("expires")
    public String getExpires() {
        return expires;
    }

    @JsonProperty("expires")
    public void setExpires(String expires) {
        this.expires = expires;
    }

    /**
     * InteractionId
     * <p>
     * An interaction by contract spec §4.2's identity: description plus state names.
     * 
     */
    @JsonProperty("interaction")
    public InteractionId getInteraction() {
        return interaction;
    }

    /**
     * InteractionId
     * <p>
     * An interaction by contract spec §4.2's identity: description plus state names.
     * 
     */
    @JsonProperty("interaction")
    public void setInteraction(InteractionId interaction) {
        this.interaction = interaction;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("matched")
    public Long getMatched() {
        return matched;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("matched")
    public void setMatched(Long matched) {
        this.matched = matched;
    }

    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    @JsonProperty("path")
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reason")
    public String getReason() {
        return reason;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * 'applied' silenced at least one finding, 'unused' matched nothing, 'lapsed' is past its own 'expires' date and silenced nothing.
     * (Required)
     * 
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    /**
     * 'applied' silenced at least one finding, 'unused' matched nothing, 'lapsed' is past its own 'expires' date and silenced nothing.
     * (Required)
     * 
     */
    @JsonProperty("status")
    public void setStatus(String status) {
        this.status = status;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ExemptionResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("consumer");
        sb.append('=');
        sb.append(((this.consumer == null)?"<null>":this.consumer));
        sb.append(',');
        sb.append("expires");
        sb.append('=');
        sb.append(((this.expires == null)?"<null>":this.expires));
        sb.append(',');
        sb.append("interaction");
        sb.append('=');
        sb.append(((this.interaction == null)?"<null>":this.interaction));
        sb.append(',');
        sb.append("matched");
        sb.append('=');
        sb.append(((this.matched == null)?"<null>":this.matched));
        sb.append(',');
        sb.append("path");
        sb.append('=');
        sb.append(((this.path == null)?"<null>":this.path));
        sb.append(',');
        sb.append("reason");
        sb.append('=');
        sb.append(((this.reason == null)?"<null>":this.reason));
        sb.append(',');
        sb.append("status");
        sb.append('=');
        sb.append(((this.status == null)?"<null>":this.status));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.path == null)? 0 :this.path.hashCode()));
        result = ((result* 31)+((this.reason == null)? 0 :this.reason.hashCode()));
        result = ((result* 31)+((this.expires == null)? 0 :this.expires.hashCode()));
        result = ((result* 31)+((this.interaction == null)? 0 :this.interaction.hashCode()));
        result = ((result* 31)+((this.matched == null)? 0 :this.matched.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.consumer == null)? 0 :this.consumer.hashCode()));
        result = ((result* 31)+((this.status == null)? 0 :this.status.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ExemptionResult) == false) {
            return false;
        }
        ExemptionResult rhs = ((ExemptionResult) other);
        return (((((((((this.path == rhs.path)||((this.path!= null)&&this.path.equals(rhs.path)))&&((this.reason == rhs.reason)||((this.reason!= null)&&this.reason.equals(rhs.reason))))&&((this.expires == rhs.expires)||((this.expires!= null)&&this.expires.equals(rhs.expires))))&&((this.interaction == rhs.interaction)||((this.interaction!= null)&&this.interaction.equals(rhs.interaction))))&&((this.matched == rhs.matched)||((this.matched!= null)&&this.matched.equals(rhs.matched))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.consumer == rhs.consumer)||((this.consumer!= null)&&this.consumer.equals(rhs.consumer))))&&((this.status == rhs.status)||((this.status!= null)&&this.status.equals(rhs.status))));
    }

}
