/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Explain
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "interaction",
    "options"
})
public class Explain {

    /**
     * ExplainSubject
     * <p>
     * What to compile: an interaction specification or one interaction from a contract document.
     * (Required)
     * 
     */
    @JsonProperty("interaction")
    @JsonPropertyDescription("What to compile: an interaction specification or one interaction from a contract document.")
    private ExplainSubject interaction;
    @JsonProperty("options")
    private Map<String, Object> options;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * ExplainSubject
     * <p>
     * What to compile: an interaction specification or one interaction from a contract document.
     * (Required)
     * 
     */
    @JsonProperty("interaction")
    public ExplainSubject getInteraction() {
        return interaction;
    }

    /**
     * ExplainSubject
     * <p>
     * What to compile: an interaction specification or one interaction from a contract document.
     * (Required)
     * 
     */
    @JsonProperty("interaction")
    public void setInteraction(ExplainSubject interaction) {
        this.interaction = interaction;
    }

    @JsonProperty("options")
    public Map<String, Object> getOptions() {
        return options;
    }

    @JsonProperty("options")
    public void setOptions(Map<String, Object> options) {
        this.options = options;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Explain.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("interaction");
        sb.append('=');
        sb.append(((this.interaction == null)?"<null>":this.interaction));
        sb.append(',');
        sb.append("options");
        sb.append('=');
        sb.append(((this.options == null)?"<null>":this.options));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.interaction == null)? 0 :this.interaction.hashCode()));
        result = ((result* 31)+((this.options == null)? 0 :this.options.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Explain) == false) {
            return false;
        }
        Explain rhs = ((Explain) other);
        return ((((this.interaction == rhs.interaction)||((this.interaction!= null)&&this.interaction.equals(rhs.interaction)))&&((this.options == rhs.options)||((this.options!= null)&&this.options.equals(rhs.options))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
