/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ExplainSubject
 * <p>
 * What to compile: an interaction specification or one interaction from a contract document.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "contract",
    "index",
    "kind",
    "spec"
})
public class ExplainSubject {

    /**
     * For kind 'contract-interaction': the contract document (a Janus contract or a v1–v4 pact).
     * 
     */
    @JsonProperty("contract")
    @JsonPropertyDescription("For kind 'contract-interaction': the contract document (a Janus contract or a v1\u2013v4 pact).")
    private Map<String, Object> contract;
    /**
     * For kind 'contract-interaction': which interaction.
     * 
     */
    @JsonProperty("index")
    @JsonPropertyDescription("For kind 'contract-interaction': which interaction.")
    private Long index;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("kind")
    private java.lang.String kind;
    /**
     * For kind 'spec': the interaction specification.
     * 
     */
    @JsonProperty("spec")
    @JsonPropertyDescription("For kind 'spec': the interaction specification.")
    private Map<String, Object> spec;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * For kind 'contract-interaction': the contract document (a Janus contract or a v1–v4 pact).
     * 
     */
    @JsonProperty("contract")
    public Map<String, Object> getContract() {
        return contract;
    }

    /**
     * For kind 'contract-interaction': the contract document (a Janus contract or a v1–v4 pact).
     * 
     */
    @JsonProperty("contract")
    public void setContract(Map<String, Object> contract) {
        this.contract = contract;
    }

    /**
     * For kind 'contract-interaction': which interaction.
     * 
     */
    @JsonProperty("index")
    public Long getIndex() {
        return index;
    }

    /**
     * For kind 'contract-interaction': which interaction.
     * 
     */
    @JsonProperty("index")
    public void setIndex(Long index) {
        this.index = index;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public java.lang.String getKind() {
        return kind;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public void setKind(java.lang.String kind) {
        this.kind = kind;
    }

    /**
     * For kind 'spec': the interaction specification.
     * 
     */
    @JsonProperty("spec")
    public Map<String, Object> getSpec() {
        return spec;
    }

    /**
     * For kind 'spec': the interaction specification.
     * 
     */
    @JsonProperty("spec")
    public void setSpec(Map<String, Object> spec) {
        this.spec = spec;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ExplainSubject.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("contract");
        sb.append('=');
        sb.append(((this.contract == null)?"<null>":this.contract));
        sb.append(',');
        sb.append("index");
        sb.append('=');
        sb.append(((this.index == null)?"<null>":this.index));
        sb.append(',');
        sb.append("kind");
        sb.append('=');
        sb.append(((this.kind == null)?"<null>":this.kind));
        sb.append(',');
        sb.append("spec");
        sb.append('=');
        sb.append(((this.spec == null)?"<null>":this.spec));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.index == null)? 0 :this.index.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.kind == null)? 0 :this.kind.hashCode()));
        result = ((result* 31)+((this.spec == null)? 0 :this.spec.hashCode()));
        result = ((result* 31)+((this.contract == null)? 0 :this.contract.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ExplainSubject) == false) {
            return false;
        }
        ExplainSubject rhs = ((ExplainSubject) other);
        return ((((((this.index == rhs.index)||((this.index!= null)&&this.index.equals(rhs.index)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.kind == rhs.kind)||((this.kind!= null)&&this.kind.equals(rhs.kind))))&&((this.spec == rhs.spec)||((this.spec!= null)&&this.spec.equals(rhs.spec))))&&((this.contract == rhs.contract)||((this.contract!= null)&&this.contract.equals(rhs.contract))));
    }

}
