/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * FinaliseRecordingResult
 * <p>
 * The recorded document, and the end of the session. Always produced: unlike a consumer session's finalise, there is no honesty rule to apply, because a provider shape claims only that these responses were produced, never that a test passed.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "provider-shape"
})
public class FinaliseRecordingResult {

    /**
     * Design 2.8's ProviderShape document, with provenance 'recorded'. Opaque here.
     * (Required)
     * 
     */
    @JsonProperty("provider-shape")
    @JsonPropertyDescription("Design 2.8's ProviderShape document, with provenance 'recorded'. Opaque here.")
    private Map<String, Object> providerShape;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Design 2.8's ProviderShape document, with provenance 'recorded'. Opaque here.
     * (Required)
     * 
     */
    @JsonProperty("provider-shape")
    public Map<String, Object> getProviderShape() {
        return providerShape;
    }

    /**
     * Design 2.8's ProviderShape document, with provenance 'recorded'. Opaque here.
     * (Required)
     * 
     */
    @JsonProperty("provider-shape")
    public void setProviderShape(Map<String, Object> providerShape) {
        this.providerShape = providerShape;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(FinaliseRecordingResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("providerShape");
        sb.append('=');
        sb.append(((this.providerShape == null)?"<null>":this.providerShape));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.providerShape == null)? 0 :this.providerShape.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof FinaliseRecordingResult) == false) {
            return false;
        }
        FinaliseRecordingResult rhs = ((FinaliseRecordingResult) other);
        return (((this.providerShape == rhs.providerShape)||((this.providerShape!= null)&&this.providerShape.equals(rhs.providerShape)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
