/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Hello
 * <p>
 * Request body of 'engine/hello', the mandatory first operation on every pipe. Result is HelloResult. See spec.md §5.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "capabilities",
    "host",
    "protocol-versions"
})
public class Hello {

    /**
     * Capabilities
     * <p>
     * Member names are an open vocabulary; each value is an object whose shape is defined where the capability is defined ({} when presence alone is the signal). Unknown names are ignored. v1 defines: push-events, encoding, provider-shape-recording, subsumption-check, components.
     * 
     */
    @JsonProperty("capabilities")
    @JsonPropertyDescription("Member names are an open vocabulary; each value is an object whose shape is defined where the capability is defined ({} when presence alone is the signal). Unknown names are ignored. v1 defines: push-events, encoding, provider-shape-recording, subsumption-check, components.")
    private Capabilities capabilities;
    /**
     * PartyInfo
     * <p>
     * Identification for diagnostics only; protocol semantics never depend on it.
     * 
     */
    @JsonProperty("host")
    @JsonPropertyDescription("Identification for diagnostics only; protocol semantics never depend on it.")
    private PartyInfo host;
    /**
     * Protocol major versions the host can speak, in preference order.
     * (Required)
     * 
     */
    @JsonProperty("protocol-versions")
    @JsonPropertyDescription("Protocol major versions the host can speak, in preference order.")
    private List<Long> protocolVersions;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Capabilities
     * <p>
     * Member names are an open vocabulary; each value is an object whose shape is defined where the capability is defined ({} when presence alone is the signal). Unknown names are ignored. v1 defines: push-events, encoding, provider-shape-recording, subsumption-check, components.
     * 
     */
    @JsonProperty("capabilities")
    public Capabilities getCapabilities() {
        return capabilities;
    }

    /**
     * Capabilities
     * <p>
     * Member names are an open vocabulary; each value is an object whose shape is defined where the capability is defined ({} when presence alone is the signal). Unknown names are ignored. v1 defines: push-events, encoding, provider-shape-recording, subsumption-check, components.
     * 
     */
    @JsonProperty("capabilities")
    public void setCapabilities(Capabilities capabilities) {
        this.capabilities = capabilities;
    }

    /**
     * PartyInfo
     * <p>
     * Identification for diagnostics only; protocol semantics never depend on it.
     * 
     */
    @JsonProperty("host")
    public PartyInfo getHost() {
        return host;
    }

    /**
     * PartyInfo
     * <p>
     * Identification for diagnostics only; protocol semantics never depend on it.
     * 
     */
    @JsonProperty("host")
    public void setHost(PartyInfo host) {
        this.host = host;
    }

    /**
     * Protocol major versions the host can speak, in preference order.
     * (Required)
     * 
     */
    @JsonProperty("protocol-versions")
    public List<Long> getProtocolVersions() {
        return protocolVersions;
    }

    /**
     * Protocol major versions the host can speak, in preference order.
     * (Required)
     * 
     */
    @JsonProperty("protocol-versions")
    public void setProtocolVersions(List<Long> protocolVersions) {
        this.protocolVersions = protocolVersions;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Hello.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("capabilities");
        sb.append('=');
        sb.append(((this.capabilities == null)?"<null>":this.capabilities));
        sb.append(',');
        sb.append("host");
        sb.append('=');
        sb.append(((this.host == null)?"<null>":this.host));
        sb.append(',');
        sb.append("protocolVersions");
        sb.append('=');
        sb.append(((this.protocolVersions == null)?"<null>":this.protocolVersions));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.host == null)? 0 :this.host.hashCode()));
        result = ((result* 31)+((this.capabilities == null)? 0 :this.capabilities.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.protocolVersions == null)? 0 :this.protocolVersions.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Hello) == false) {
            return false;
        }
        Hello rhs = ((Hello) other);
        return (((((this.host == rhs.host)||((this.host!= null)&&this.host.equals(rhs.host)))&&((this.capabilities == rhs.capabilities)||((this.capabilities!= null)&&this.capabilities.equals(rhs.capabilities))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.protocolVersions == rhs.protocolVersions)||((this.protocolVersions!= null)&&this.protocolVersions.equals(rhs.protocolVersions))));
    }

}
