/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ObserveResponseResult
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "interactions",
    "observations"
})
public class ObserveResponseResult {

    /**
     * How many distinct interactions those responses covered.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    @JsonPropertyDescription("How many distinct interactions those responses covered.")
    private Long interactions;
    /**
     * How many responses this session has recorded in total, so a host can report progress without holding its own counters.
     * (Required)
     * 
     */
    @JsonProperty("observations")
    @JsonPropertyDescription("How many responses this session has recorded in total, so a host can report progress without holding its own counters.")
    private Long observations;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * How many distinct interactions those responses covered.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public Long getInteractions() {
        return interactions;
    }

    /**
     * How many distinct interactions those responses covered.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public void setInteractions(Long interactions) {
        this.interactions = interactions;
    }

    /**
     * How many responses this session has recorded in total, so a host can report progress without holding its own counters.
     * (Required)
     * 
     */
    @JsonProperty("observations")
    public Long getObservations() {
        return observations;
    }

    /**
     * How many responses this session has recorded in total, so a host can report progress without holding its own counters.
     * (Required)
     * 
     */
    @JsonProperty("observations")
    public void setObservations(Long observations) {
        this.observations = observations;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ObserveResponseResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("interactions");
        sb.append('=');
        sb.append(((this.interactions == null)?"<null>":this.interactions));
        sb.append(',');
        sb.append("observations");
        sb.append('=');
        sb.append(((this.observations == null)?"<null>":this.observations));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.interactions == null)? 0 :this.interactions.hashCode()));
        result = ((result* 31)+((this.observations == null)? 0 :this.observations.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ObserveResponseResult) == false) {
            return false;
        }
        ObserveResponseResult rhs = ((ObserveResponseResult) other);
        return ((((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties)))&&((this.interactions == rhs.interactions)||((this.interactions!= null)&&this.interactions.equals(rhs.interactions))))&&((this.observations == rhs.observations)||((this.observations!= null)&&this.observations.equals(rhs.observations))));
    }

}
