/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ObservedSlotValue
 * <p>
 * One slot's value, wrapped the way contract spec §5.3 wraps one, so a host that already builds those has nothing new to learn.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "content",
    "content-type",
    "encoded"
})
public class ObservedSlotValue {

    /**
     * The decoded value, any JSON value including null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    @JsonPropertyDescription("The decoded value, any JSON value including null.")
    private Object content;
    /**
     * Advisory: what the host believes the slot carried. Not interpreted.
     * 
     */
    @JsonProperty("content-type")
    @JsonPropertyDescription("Advisory: what the host believes the slot carried. Not interpreted.")
    private String contentType;
    /**
     * Representation tag for 'content' (spec.md §2.4-2.5). Absent means the natural JSON value; 'base64' means content is a string carrying the base64 of an octet sequence, which is recorded as that string.
     * 
     */
    @JsonProperty("encoded")
    @JsonPropertyDescription("Representation tag for 'content' (spec.md \u00a72.4-2.5). Absent means the natural JSON value; 'base64' means content is a string carrying the base64 of an octet sequence, which is recorded as that string.")
    private String encoded;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * The decoded value, any JSON value including null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    public Object getContent() {
        return content;
    }

    /**
     * The decoded value, any JSON value including null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    public void setContent(Object content) {
        this.content = content;
    }

    /**
     * Advisory: what the host believes the slot carried. Not interpreted.
     * 
     */
    @JsonProperty("content-type")
    public String getContentType() {
        return contentType;
    }

    /**
     * Advisory: what the host believes the slot carried. Not interpreted.
     * 
     */
    @JsonProperty("content-type")
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Representation tag for 'content' (spec.md §2.4-2.5). Absent means the natural JSON value; 'base64' means content is a string carrying the base64 of an octet sequence, which is recorded as that string.
     * 
     */
    @JsonProperty("encoded")
    public String getEncoded() {
        return encoded;
    }

    /**
     * Representation tag for 'content' (spec.md §2.4-2.5). Absent means the natural JSON value; 'base64' means content is a string carrying the base64 of an octet sequence, which is recorded as that string.
     * 
     */
    @JsonProperty("encoded")
    public void setEncoded(String encoded) {
        this.encoded = encoded;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ObservedSlotValue.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("content");
        sb.append('=');
        sb.append(((this.content == null)?"<null>":this.content));
        sb.append(',');
        sb.append("contentType");
        sb.append('=');
        sb.append(((this.contentType == null)?"<null>":this.contentType));
        sb.append(',');
        sb.append("encoded");
        sb.append('=');
        sb.append(((this.encoded == null)?"<null>":this.encoded));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.contentType == null)? 0 :this.contentType.hashCode()));
        result = ((result* 31)+((this.content == null)? 0 :this.content.hashCode()));
        result = ((result* 31)+((this.encoded == null)? 0 :this.encoded.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ObservedSlotValue) == false) {
            return false;
        }
        ObservedSlotValue rhs = ((ObservedSlotValue) other);
        return (((((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties)))&&((this.contentType == rhs.contentType)||((this.contentType!= null)&&this.contentType.equals(rhs.contentType))))&&((this.content == rhs.content)||((this.content!= null)&&this.content.equals(rhs.content))))&&((this.encoded == rhs.encoded)||((this.encoded!= null)&&this.encoded.equals(rhs.encoded))));
    }

}
