/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * PolicyView
 * <p>
 * The policy this run resolved to, recorded because design 2.8 §7.1's layering means the answer is in no single file.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "exemptions",
    "on-finding",
    "on-review"
})
public class PolicyView {

    /**
     * How many exemptions were in force across every layer.
     * (Required)
     * 
     */
    @JsonProperty("exemptions")
    @JsonPropertyDescription("How many exemptions were in force across every layer.")
    private Long exemptions;
    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-finding")
    @JsonPropertyDescription("What a subsumption severity does to the run (design 2.8 \u00a77.1). Both default to 'warn' (ADR 0016).")
    private String onFinding;
    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-review")
    @JsonPropertyDescription("What a subsumption severity does to the run (design 2.8 \u00a77.1). Both default to 'warn' (ADR 0016).")
    private String onReview;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * How many exemptions were in force across every layer.
     * (Required)
     * 
     */
    @JsonProperty("exemptions")
    public Long getExemptions() {
        return exemptions;
    }

    /**
     * How many exemptions were in force across every layer.
     * (Required)
     * 
     */
    @JsonProperty("exemptions")
    public void setExemptions(Long exemptions) {
        this.exemptions = exemptions;
    }

    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-finding")
    public String getOnFinding() {
        return onFinding;
    }

    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-finding")
    public void setOnFinding(String onFinding) {
        this.onFinding = onFinding;
    }

    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-review")
    public String getOnReview() {
        return onReview;
    }

    /**
     * PolicyAction
     * <p>
     * What a subsumption severity does to the run (design 2.8 §7.1). Both default to 'warn' (ADR 0016).
     * (Required)
     * 
     */
    @JsonProperty("on-review")
    public void setOnReview(String onReview) {
        this.onReview = onReview;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(PolicyView.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("exemptions");
        sb.append('=');
        sb.append(((this.exemptions == null)?"<null>":this.exemptions));
        sb.append(',');
        sb.append("onFinding");
        sb.append('=');
        sb.append(((this.onFinding == null)?"<null>":this.onFinding));
        sb.append(',');
        sb.append("onReview");
        sb.append('=');
        sb.append(((this.onReview == null)?"<null>":this.onReview));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.onFinding == null)? 0 :this.onFinding.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.exemptions == null)? 0 :this.exemptions.hashCode()));
        result = ((result* 31)+((this.onReview == null)? 0 :this.onReview.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof PolicyView) == false) {
            return false;
        }
        PolicyView rhs = ((PolicyView) other);
        return (((((this.onFinding == rhs.onFinding)||((this.onFinding!= null)&&this.onFinding.equals(rhs.onFinding)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.exemptions == rhs.exemptions)||((this.exemptions!= null)&&this.exemptions.equals(rhs.exemptions))))&&((this.onReview == rhs.onReview)||((this.onReview!= null)&&this.onReview.equals(rhs.onReview))));
    }

}
