/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Poll
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "max",
    "streams",
    "wait-ms"
})
public class Poll {

    /**
     * Maximum events to return; default is the engine's choice.
     * 
     */
    @JsonProperty("max")
    @JsonPropertyDescription("Maximum events to return; default is the engine's choice.")
    private Long max;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("streams")
    private List<String> streams;
    /**
     * Long-poll: the engine may hold the response up to this long when no events are pending.
     * 
     */
    @JsonProperty("wait-ms")
    @JsonPropertyDescription("Long-poll: the engine may hold the response up to this long when no events are pending.")
    private Long waitMs;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Maximum events to return; default is the engine's choice.
     * 
     */
    @JsonProperty("max")
    public Long getMax() {
        return max;
    }

    /**
     * Maximum events to return; default is the engine's choice.
     * 
     */
    @JsonProperty("max")
    public void setMax(Long max) {
        this.max = max;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("streams")
    public List<String> getStreams() {
        return streams;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("streams")
    public void setStreams(List<String> streams) {
        this.streams = streams;
    }

    /**
     * Long-poll: the engine may hold the response up to this long when no events are pending.
     * 
     */
    @JsonProperty("wait-ms")
    public Long getWaitMs() {
        return waitMs;
    }

    /**
     * Long-poll: the engine may hold the response up to this long when no events are pending.
     * 
     */
    @JsonProperty("wait-ms")
    public void setWaitMs(Long waitMs) {
        this.waitMs = waitMs;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Poll.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("max");
        sb.append('=');
        sb.append(((this.max == null)?"<null>":this.max));
        sb.append(',');
        sb.append("streams");
        sb.append('=');
        sb.append(((this.streams == null)?"<null>":this.streams));
        sb.append(',');
        sb.append("waitMs");
        sb.append('=');
        sb.append(((this.waitMs == null)?"<null>":this.waitMs));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.waitMs == null)? 0 :this.waitMs.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.max == null)? 0 :this.max.hashCode()));
        result = ((result* 31)+((this.streams == null)? 0 :this.streams.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Poll) == false) {
            return false;
        }
        Poll rhs = ((Poll) other);
        return (((((this.waitMs == rhs.waitMs)||((this.waitMs!= null)&&this.waitMs.equals(rhs.waitMs)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.max == rhs.max)||((this.max!= null)&&this.max.equals(rhs.max))))&&((this.streams == rhs.streams)||((this.streams!= null)&&this.streams.equals(rhs.streams))));
    }

}
