/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RequestFrame
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "body",
    "id",
    "op",
    "type"
})
public class RequestFrame {

    /**
     * The operation's request document, governed by the operation's schema.
     * (Required)
     * 
     */
    @JsonProperty("body")
    @JsonPropertyDescription("The operation's request document, governed by the operation's schema.")
    private Map<String, Object> body;
    /**
     * Host-chosen correlation id, unique among the host's in-flight requests on this pipe. Opaque to the engine.
     * (Required)
     * 
     */
    @JsonProperty("id")
    @JsonPropertyDescription("Host-chosen correlation id, unique among the host's in-flight requests on this pipe. Opaque to the engine.")
    private java.lang.String id;
    /**
     * Operation name, namespaced '<area>/<verb>'. Open vocabulary; unknown ops are answered with error 'operation-unsupported'.
     * (Required)
     * 
     */
    @JsonProperty("op")
    @JsonPropertyDescription("Operation name, namespaced '<area>/<verb>'. Open vocabulary; unknown ops are answered with error 'operation-unsupported'.")
    private java.lang.String op;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("type")
    private java.lang.String type;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * The operation's request document, governed by the operation's schema.
     * (Required)
     * 
     */
    @JsonProperty("body")
    public Map<String, Object> getBody() {
        return body;
    }

    /**
     * The operation's request document, governed by the operation's schema.
     * (Required)
     * 
     */
    @JsonProperty("body")
    public void setBody(Map<String, Object> body) {
        this.body = body;
    }

    /**
     * Host-chosen correlation id, unique among the host's in-flight requests on this pipe. Opaque to the engine.
     * (Required)
     * 
     */
    @JsonProperty("id")
    public java.lang.String getId() {
        return id;
    }

    /**
     * Host-chosen correlation id, unique among the host's in-flight requests on this pipe. Opaque to the engine.
     * (Required)
     * 
     */
    @JsonProperty("id")
    public void setId(java.lang.String id) {
        this.id = id;
    }

    /**
     * Operation name, namespaced '<area>/<verb>'. Open vocabulary; unknown ops are answered with error 'operation-unsupported'.
     * (Required)
     * 
     */
    @JsonProperty("op")
    public java.lang.String getOp() {
        return op;
    }

    /**
     * Operation name, namespaced '<area>/<verb>'. Open vocabulary; unknown ops are answered with error 'operation-unsupported'.
     * (Required)
     * 
     */
    @JsonProperty("op")
    public void setOp(java.lang.String op) {
        this.op = op;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("type")
    public java.lang.String getType() {
        return type;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("type")
    public void setType(java.lang.String type) {
        this.type = type;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(RequestFrame.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("body");
        sb.append('=');
        sb.append(((this.body == null)?"<null>":this.body));
        sb.append(',');
        sb.append("id");
        sb.append('=');
        sb.append(((this.id == null)?"<null>":this.id));
        sb.append(',');
        sb.append("op");
        sb.append('=');
        sb.append(((this.op == null)?"<null>":this.op));
        sb.append(',');
        sb.append("type");
        sb.append('=');
        sb.append(((this.type == null)?"<null>":this.type));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.op == null)? 0 :this.op.hashCode()));
        result = ((result* 31)+((this.id == null)? 0 :this.id.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.body == null)? 0 :this.body.hashCode()));
        result = ((result* 31)+((this.type == null)? 0 :this.type.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof RequestFrame) == false) {
            return false;
        }
        RequestFrame rhs = ((RequestFrame) other);
        return ((((((this.op == rhs.op)||((this.op!= null)&&this.op.equals(rhs.op)))&&((this.id == rhs.id)||((this.id!= null)&&this.id.equals(rhs.id))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.body == rhs.body)||((this.body!= null)&&this.body.equals(rhs.body))))&&((this.type == rhs.type)||((this.type!= null)&&this.type.equals(rhs.type))));
    }

}
