/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SubsumptionView
 * <p>
 * What the subsumption report says about this pair, after policy.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "advisories",
    "exempt",
    "findings",
    "interactions",
    "matched",
    "not-published",
    "reviews",
    "verdict"
})
public class SubsumptionView {

    /**
     * 'advisory' entries (design 2.8 §5), which no policy governs and no exemption silences.
     * (Required)
     * 
     */
    @JsonProperty("advisories")
    @JsonPropertyDescription("'advisory' entries (design 2.8 \u00a75), which no policy governs and no exemption silences.")
    private Long advisories;
    /**
     * Results of either severity an exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    @JsonPropertyDescription("Results of either severity an exemption silenced.")
    private Long exempt;
    /**
     * 'finding'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("findings")
    @JsonPropertyDescription("'finding'-severity results no exemption silenced.")
    private Long findings;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    private Long interactions;
    /**
     * Interactions with a published provider-shape entry (design 2.8 §2.2).
     * (Required)
     * 
     */
    @JsonProperty("matched")
    @JsonPropertyDescription("Interactions with a published provider-shape entry (design 2.8 \u00a72.2).")
    private Long matched;
    /**
     * Interactions the provider published nothing for, which were therefore not checked (design 2.8 §6.3).
     * (Required)
     * 
     */
    @JsonProperty("not-published")
    @JsonPropertyDescription("Interactions the provider published nothing for, which were therefore not checked (design 2.8 \u00a76.3).")
    private Long notPublished;
    /**
     * 'review'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    @JsonPropertyDescription("'review'-severity results no exemption silenced.")
    private Long reviews;
    /**
     * The walk's own aggregate verdict, unchanged by policy: an exempted finding is still a 'no'. 'not-checked' means no report was attached.
     * (Required)
     * 
     */
    @JsonProperty("verdict")
    @JsonPropertyDescription("The walk's own aggregate verdict, unchanged by policy: an exempted finding is still a 'no'. 'not-checked' means no report was attached.")
    private String verdict;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 'advisory' entries (design 2.8 §5), which no policy governs and no exemption silences.
     * (Required)
     * 
     */
    @JsonProperty("advisories")
    public Long getAdvisories() {
        return advisories;
    }

    /**
     * 'advisory' entries (design 2.8 §5), which no policy governs and no exemption silences.
     * (Required)
     * 
     */
    @JsonProperty("advisories")
    public void setAdvisories(Long advisories) {
        this.advisories = advisories;
    }

    /**
     * Results of either severity an exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    public Long getExempt() {
        return exempt;
    }

    /**
     * Results of either severity an exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("exempt")
    public void setExempt(Long exempt) {
        this.exempt = exempt;
    }

    /**
     * 'finding'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public Long getFindings() {
        return findings;
    }

    /**
     * 'finding'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public void setFindings(Long findings) {
        this.findings = findings;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public Long getInteractions() {
        return interactions;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public void setInteractions(Long interactions) {
        this.interactions = interactions;
    }

    /**
     * Interactions with a published provider-shape entry (design 2.8 §2.2).
     * (Required)
     * 
     */
    @JsonProperty("matched")
    public Long getMatched() {
        return matched;
    }

    /**
     * Interactions with a published provider-shape entry (design 2.8 §2.2).
     * (Required)
     * 
     */
    @JsonProperty("matched")
    public void setMatched(Long matched) {
        this.matched = matched;
    }

    /**
     * Interactions the provider published nothing for, which were therefore not checked (design 2.8 §6.3).
     * (Required)
     * 
     */
    @JsonProperty("not-published")
    public Long getNotPublished() {
        return notPublished;
    }

    /**
     * Interactions the provider published nothing for, which were therefore not checked (design 2.8 §6.3).
     * (Required)
     * 
     */
    @JsonProperty("not-published")
    public void setNotPublished(Long notPublished) {
        this.notPublished = notPublished;
    }

    /**
     * 'review'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    public Long getReviews() {
        return reviews;
    }

    /**
     * 'review'-severity results no exemption silenced.
     * (Required)
     * 
     */
    @JsonProperty("reviews")
    public void setReviews(Long reviews) {
        this.reviews = reviews;
    }

    /**
     * The walk's own aggregate verdict, unchanged by policy: an exempted finding is still a 'no'. 'not-checked' means no report was attached.
     * (Required)
     * 
     */
    @JsonProperty("verdict")
    public String getVerdict() {
        return verdict;
    }

    /**
     * The walk's own aggregate verdict, unchanged by policy: an exempted finding is still a 'no'. 'not-checked' means no report was attached.
     * (Required)
     * 
     */
    @JsonProperty("verdict")
    public void setVerdict(String verdict) {
        this.verdict = verdict;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(SubsumptionView.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("advisories");
        sb.append('=');
        sb.append(((this.advisories == null)?"<null>":this.advisories));
        sb.append(',');
        sb.append("exempt");
        sb.append('=');
        sb.append(((this.exempt == null)?"<null>":this.exempt));
        sb.append(',');
        sb.append("findings");
        sb.append('=');
        sb.append(((this.findings == null)?"<null>":this.findings));
        sb.append(',');
        sb.append("interactions");
        sb.append('=');
        sb.append(((this.interactions == null)?"<null>":this.interactions));
        sb.append(',');
        sb.append("matched");
        sb.append('=');
        sb.append(((this.matched == null)?"<null>":this.matched));
        sb.append(',');
        sb.append("notPublished");
        sb.append('=');
        sb.append(((this.notPublished == null)?"<null>":this.notPublished));
        sb.append(',');
        sb.append("reviews");
        sb.append('=');
        sb.append(((this.reviews == null)?"<null>":this.reviews));
        sb.append(',');
        sb.append("verdict");
        sb.append('=');
        sb.append(((this.verdict == null)?"<null>":this.verdict));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.advisories == null)? 0 :this.advisories.hashCode()));
        result = ((result* 31)+((this.reviews == null)? 0 :this.reviews.hashCode()));
        result = ((result* 31)+((this.notPublished == null)? 0 :this.notPublished.hashCode()));
        result = ((result* 31)+((this.findings == null)? 0 :this.findings.hashCode()));
        result = ((result* 31)+((this.verdict == null)? 0 :this.verdict.hashCode()));
        result = ((result* 31)+((this.matched == null)? 0 :this.matched.hashCode()));
        result = ((result* 31)+((this.exempt == null)? 0 :this.exempt.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.interactions == null)? 0 :this.interactions.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof SubsumptionView) == false) {
            return false;
        }
        SubsumptionView rhs = ((SubsumptionView) other);
        return ((((((((((this.advisories == rhs.advisories)||((this.advisories!= null)&&this.advisories.equals(rhs.advisories)))&&((this.reviews == rhs.reviews)||((this.reviews!= null)&&this.reviews.equals(rhs.reviews))))&&((this.notPublished == rhs.notPublished)||((this.notPublished!= null)&&this.notPublished.equals(rhs.notPublished))))&&((this.findings == rhs.findings)||((this.findings!= null)&&this.findings.equals(rhs.findings))))&&((this.verdict == rhs.verdict)||((this.verdict!= null)&&this.verdict.equals(rhs.verdict))))&&((this.matched == rhs.matched)||((this.matched!= null)&&this.matched.equals(rhs.matched))))&&((this.exempt == rhs.exempt)||((this.exempt!= null)&&this.exempt.equals(rhs.exempt))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.interactions == rhs.interactions)||((this.interactions!= null)&&this.interactions.equals(rhs.interactions))));
    }

}
