/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * UpgradeFinding
 * <p>
 * One conversion finding. The normative definition is contract-file spec §8.4 (its schemas/v1/upgrade-findings.schema.json); this mirrors it so a host validating a frame against this file alone is checking the same document.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "code",
    "kind",
    "message",
    "path",
    "target"
})
public class UpgradeFinding {

    /**
     * Open vocabulary; an unknown code is displayed, never dispatched on. Codes are listed in contract-file spec §8.4.
     * (Required)
     * 
     */
    @JsonProperty("code")
    @JsonPropertyDescription("Open vocabulary; an unknown code is displayed, never dispatched on. Codes are listed in contract-file spec \u00a78.4.")
    private String code;
    /**
     * 'lossy' means the contract now says less than the pact did; 'judgement' means the converter chose between readings the pact did not distinguish; 'note' means neither, and is worth reading anyway.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    @JsonPropertyDescription("'lossy' means the contract now says less than the pact did; 'judgement' means the converter chose between readings the pact did not distinguish; 'note' means neither, and is worth reading anyway.")
    private String kind;
    /**
     * Prose, addressed to the author of the pact.
     * (Required)
     * 
     */
    @JsonProperty("message")
    @JsonPropertyDescription("Prose, addressed to the author of the pact.")
    private String message;
    /**
     * RFC 6901 JSON pointer into the *source pact* — the file the author is looking at.
     * (Required)
     * 
     */
    @JsonProperty("path")
    @JsonPropertyDescription("RFC 6901 JSON pointer into the *source pact* \u2014 the file the author is looking at.")
    private String path;
    /**
     * RFC 6901 JSON pointer into the converted contract, where the source construct ended up, when there is such a place.
     * 
     */
    @JsonProperty("target")
    @JsonPropertyDescription("RFC 6901 JSON pointer into the converted contract, where the source construct ended up, when there is such a place.")
    private String target;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * Open vocabulary; an unknown code is displayed, never dispatched on. Codes are listed in contract-file spec §8.4.
     * (Required)
     * 
     */
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    /**
     * Open vocabulary; an unknown code is displayed, never dispatched on. Codes are listed in contract-file spec §8.4.
     * (Required)
     * 
     */
    @JsonProperty("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 'lossy' means the contract now says less than the pact did; 'judgement' means the converter chose between readings the pact did not distinguish; 'note' means neither, and is worth reading anyway.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public String getKind() {
        return kind;
    }

    /**
     * 'lossy' means the contract now says less than the pact did; 'judgement' means the converter chose between readings the pact did not distinguish; 'note' means neither, and is worth reading anyway.
     * (Required)
     * 
     */
    @JsonProperty("kind")
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Prose, addressed to the author of the pact.
     * (Required)
     * 
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     * Prose, addressed to the author of the pact.
     * (Required)
     * 
     */
    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * RFC 6901 JSON pointer into the *source pact* — the file the author is looking at.
     * (Required)
     * 
     */
    @JsonProperty("path")
    public String getPath() {
        return path;
    }

    /**
     * RFC 6901 JSON pointer into the *source pact* — the file the author is looking at.
     * (Required)
     * 
     */
    @JsonProperty("path")
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * RFC 6901 JSON pointer into the converted contract, where the source construct ended up, when there is such a place.
     * 
     */
    @JsonProperty("target")
    public String getTarget() {
        return target;
    }

    /**
     * RFC 6901 JSON pointer into the converted contract, where the source construct ended up, when there is such a place.
     * 
     */
    @JsonProperty("target")
    public void setTarget(String target) {
        this.target = target;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(UpgradeFinding.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("code");
        sb.append('=');
        sb.append(((this.code == null)?"<null>":this.code));
        sb.append(',');
        sb.append("kind");
        sb.append('=');
        sb.append(((this.kind == null)?"<null>":this.kind));
        sb.append(',');
        sb.append("message");
        sb.append('=');
        sb.append(((this.message == null)?"<null>":this.message));
        sb.append(',');
        sb.append("path");
        sb.append('=');
        sb.append(((this.path == null)?"<null>":this.path));
        sb.append(',');
        sb.append("target");
        sb.append('=');
        sb.append(((this.target == null)?"<null>":this.target));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.path == null)? 0 :this.path.hashCode()));
        result = ((result* 31)+((this.code == null)? 0 :this.code.hashCode()));
        result = ((result* 31)+((this.kind == null)? 0 :this.kind.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.message == null)? 0 :this.message.hashCode()));
        result = ((result* 31)+((this.target == null)? 0 :this.target.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof UpgradeFinding) == false) {
            return false;
        }
        UpgradeFinding rhs = ((UpgradeFinding) other);
        return (((((((this.path == rhs.path)||((this.path!= null)&&this.path.equals(rhs.path)))&&((this.code == rhs.code)||((this.code!= null)&&this.code.equals(rhs.code))))&&((this.kind == rhs.kind)||((this.kind!= null)&&this.kind.equals(rhs.kind))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.message == rhs.message)||((this.message!= null)&&this.message.equals(rhs.message))))&&((this.target == rhs.target)||((this.target!= null)&&this.target.equals(rhs.target))));
    }

}
