/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Variants
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "handle",
    "policy",
    "session"
})
public class Variants {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("handle")
    private java.lang.String handle;
    /**
     * Per-call sampling policy override (design 2.3), for a host offering an '--exhaustive'-style switch. The resolution order is spec-defaults, session config, interaction spec, then this.
     * 
     */
    @JsonProperty("policy")
    @JsonPropertyDescription("Per-call sampling policy override (design 2.3), for a host offering an '--exhaustive'-style switch. The resolution order is spec-defaults, session config, interaction spec, then this.")
    private Map<String, Object> policy;
    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("session")
    private java.lang.String session;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("handle")
    public java.lang.String getHandle() {
        return handle;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("handle")
    public void setHandle(java.lang.String handle) {
        this.handle = handle;
    }

    /**
     * Per-call sampling policy override (design 2.3), for a host offering an '--exhaustive'-style switch. The resolution order is spec-defaults, session config, interaction spec, then this.
     * 
     */
    @JsonProperty("policy")
    public Map<String, Object> getPolicy() {
        return policy;
    }

    /**
     * Per-call sampling policy override (design 2.3), for a host offering an '--exhaustive'-style switch. The resolution order is spec-defaults, session config, interaction spec, then this.
     * 
     */
    @JsonProperty("policy")
    public void setPolicy(Map<String, Object> policy) {
        this.policy = policy;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("session")
    public java.lang.String getSession() {
        return session;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("session")
    public void setSession(java.lang.String session) {
        this.session = session;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Variants.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("handle");
        sb.append('=');
        sb.append(((this.handle == null)?"<null>":this.handle));
        sb.append(',');
        sb.append("policy");
        sb.append('=');
        sb.append(((this.policy == null)?"<null>":this.policy));
        sb.append(',');
        sb.append("session");
        sb.append('=');
        sb.append(((this.session == null)?"<null>":this.session));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.handle == null)? 0 :this.handle.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.session == null)? 0 :this.session.hashCode()));
        result = ((result* 31)+((this.policy == null)? 0 :this.policy.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Variants) == false) {
            return false;
        }
        Variants rhs = ((Variants) other);
        return (((((this.handle == rhs.handle)||((this.handle!= null)&&this.handle.equals(rhs.handle)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.session == rhs.session)||((this.session!= null)&&this.session.equals(rhs.session))))&&((this.policy == rhs.policy)||((this.policy!= null)&&this.policy.equals(rhs.policy))));
    }

}
