/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * VariantsResult
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "report",
    "variants"
})
public class VariantsResult {

    /**
     * How the selection was chosen: space size, strategy, coverage, exclusions (design 2.3).
     * 
     */
    @JsonProperty("report")
    @JsonPropertyDescription("How the selection was chosen: space size, strategy, coverage, exclusions (design 2.3).")
    private Map<String, Object> report;
    /**
     * The selection, in run order — the variants the engine chose, not the whole space (design 2.3).
     * (Required)
     * 
     */
    @JsonProperty("variants")
    @JsonPropertyDescription("The selection, in run order \u2014 the variants the engine chose, not the whole space (design 2.3).")
    private List<VariantDescriptor> variants;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * How the selection was chosen: space size, strategy, coverage, exclusions (design 2.3).
     * 
     */
    @JsonProperty("report")
    public Map<String, Object> getReport() {
        return report;
    }

    /**
     * How the selection was chosen: space size, strategy, coverage, exclusions (design 2.3).
     * 
     */
    @JsonProperty("report")
    public void setReport(Map<String, Object> report) {
        this.report = report;
    }

    /**
     * The selection, in run order — the variants the engine chose, not the whole space (design 2.3).
     * (Required)
     * 
     */
    @JsonProperty("variants")
    public List<VariantDescriptor> getVariants() {
        return variants;
    }

    /**
     * The selection, in run order — the variants the engine chose, not the whole space (design 2.3).
     * (Required)
     * 
     */
    @JsonProperty("variants")
    public void setVariants(List<VariantDescriptor> variants) {
        this.variants = variants;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(VariantsResult.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("report");
        sb.append('=');
        sb.append(((this.report == null)?"<null>":this.report));
        sb.append(',');
        sb.append("variants");
        sb.append('=');
        sb.append(((this.variants == null)?"<null>":this.variants));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.report == null)? 0 :this.report.hashCode()));
        result = ((result* 31)+((this.variants == null)? 0 :this.variants.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof VariantsResult) == false) {
            return false;
        }
        VariantsResult rhs = ((VariantsResult) other);
        return ((((this.report == rhs.report)||((this.report!= null)&&this.report.equals(rhs.report)))&&((this.variants == rhs.variants)||((this.variants!= null)&&this.variants.equals(rhs.variants))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
