/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.protocol.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Verify
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "options",
    "source",
    "target"
})
public class Verify {

    /**
     * Open, additive verification options (filtering, publishing intent, etc.).
     * 
     */
    @JsonProperty("options")
    @JsonPropertyDescription("Open, additive verification options (filtering, publishing intent, etc.).")
    private Map<String, Object> options;
    /**
     * ContractSource
     * <p>
     * Where the contracts come from — Janus contracts or v1–v4 pacts. Open vocabulary; v1 defines 'inline' — hosts fetch files/URLs/broker themselves in the prototype, keeping I/O out of the kernel.
     * (Required)
     * 
     */
    @JsonProperty("source")
    @JsonPropertyDescription("Where the contracts come from \u2014 Janus contracts or v1\u2013v4 pacts. Open vocabulary; v1 defines 'inline' \u2014 hosts fetch files/URLs/broker themselves in the prototype, keeping I/O out of the kernel.")
    private ContractSource source;
    /**
     * VerificationTarget
     * <p>
     * The provider under test: transport bindings as open descriptor documents, plus open options (state-change/hook config is design 2.7's).
     * (Required)
     * 
     */
    @JsonProperty("target")
    @JsonPropertyDescription("The provider under test: transport bindings as open descriptor documents, plus open options (state-change/hook config is design 2.7's).")
    private VerificationTarget target;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Open, additive verification options (filtering, publishing intent, etc.).
     * 
     */
    @JsonProperty("options")
    public Map<String, Object> getOptions() {
        return options;
    }

    /**
     * Open, additive verification options (filtering, publishing intent, etc.).
     * 
     */
    @JsonProperty("options")
    public void setOptions(Map<String, Object> options) {
        this.options = options;
    }

    /**
     * ContractSource
     * <p>
     * Where the contracts come from — Janus contracts or v1–v4 pacts. Open vocabulary; v1 defines 'inline' — hosts fetch files/URLs/broker themselves in the prototype, keeping I/O out of the kernel.
     * (Required)
     * 
     */
    @JsonProperty("source")
    public ContractSource getSource() {
        return source;
    }

    /**
     * ContractSource
     * <p>
     * Where the contracts come from — Janus contracts or v1–v4 pacts. Open vocabulary; v1 defines 'inline' — hosts fetch files/URLs/broker themselves in the prototype, keeping I/O out of the kernel.
     * (Required)
     * 
     */
    @JsonProperty("source")
    public void setSource(ContractSource source) {
        this.source = source;
    }

    /**
     * VerificationTarget
     * <p>
     * The provider under test: transport bindings as open descriptor documents, plus open options (state-change/hook config is design 2.7's).
     * (Required)
     * 
     */
    @JsonProperty("target")
    public VerificationTarget getTarget() {
        return target;
    }

    /**
     * VerificationTarget
     * <p>
     * The provider under test: transport bindings as open descriptor documents, plus open options (state-change/hook config is design 2.7's).
     * (Required)
     * 
     */
    @JsonProperty("target")
    public void setTarget(VerificationTarget target) {
        this.target = target;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Verify.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("options");
        sb.append('=');
        sb.append(((this.options == null)?"<null>":this.options));
        sb.append(',');
        sb.append("source");
        sb.append('=');
        sb.append(((this.source == null)?"<null>":this.source));
        sb.append(',');
        sb.append("target");
        sb.append('=');
        sb.append(((this.target == null)?"<null>":this.target));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.options == null)? 0 :this.options.hashCode()));
        result = ((result* 31)+((this.source == null)? 0 :this.source.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.target == null)? 0 :this.target.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Verify) == false) {
            return false;
        }
        Verify rhs = ((Verify) other);
        return (((((this.options == rhs.options)||((this.options!= null)&&this.options.equals(rhs.options)))&&((this.source == rhs.source)||((this.source!= null)&&this.source.equals(rhs.source))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.target == rhs.target)||((this.target!= null)&&this.target.equals(rhs.target))));
    }

}
