/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */

package io.pact.janus.bindings.protocol.v1;

import java.util.List;

/**
 * Known values of this package's open vocabularies. Values not listed here may appear and
 * must be handled by policy, never rejected (engine-protocol spec §2.2 rule 3).
 */
public final class Vocabulary {
  private Vocabulary() {}

  /** Known values of {@code ContractSource.kind}. */
  public static final class ContractSourceKind {
    private ContractSourceKind() {}

    public static final String INLINE = "inline";

    public static final List<String> KNOWN = List.of(INLINE);
  }

  /** Known values of {@code EncodingName}. */
  public static final class EncodingName {
    private EncodingName() {}

    public static final String JSON = "json";

    public static final List<String> KNOWN = List.of(JSON);
  }

  /** Known values of {@code EngineError.category}. */
  public static final class EngineErrorCategory {
    private EngineErrorCategory() {}

    public static final String PROTOCOL = "protocol";
    public static final String SESSION = "session";
    public static final String DOCUMENT = "document";
    public static final String COMPONENT = "component";
    public static final String INTERNAL = "internal";

    public static final List<String> KNOWN = List.of(PROTOCOL, SESSION, DOCUMENT, COMPONENT, INTERNAL);
  }

  /** Known values of {@code EngineError.code}. */
  public static final class EngineErrorCode {
    private EngineErrorCode() {}

    public static final String MALFORMED_FRAME = "malformed-frame";
    public static final String HANDSHAKE_REQUIRED = "handshake-required";
    public static final String PROTOCOL_VERSION_UNSUPPORTED = "protocol-version-unsupported";
    public static final String OPERATION_UNSUPPORTED = "operation-unsupported";
    public static final String CAPABILITY_REQUIRED = "capability-required";
    public static final String ENGINE_SHUT_DOWN = "engine-shut-down";
    public static final String SESSION_NOT_FOUND = "session-not-found";
    public static final String HANDLE_NOT_FOUND = "handle-not-found";
    public static final String VARIANT_NOT_FOUND = "variant-not-found";
    public static final String STREAM_NOT_FOUND = "stream-not-found";
    public static final String INTERACTION_INVALID = "interaction-invalid";
    public static final String CONTRACT_INVALID = "contract-invalid";
    public static final String CONTRACT_VERSION_UNSUPPORTED = "contract-version-unsupported";
    public static final String VARIANT_BUDGET_EXCEEDED = "variant-budget-exceeded";
    public static final String COMPONENT_UNAVAILABLE = "component-unavailable";
    public static final String COMPONENT_FAILED = "component-failed";
    public static final String INTERNAL = "internal";

    public static final List<String> KNOWN = List.of(MALFORMED_FRAME, HANDSHAKE_REQUIRED, PROTOCOL_VERSION_UNSUPPORTED, OPERATION_UNSUPPORTED, CAPABILITY_REQUIRED, ENGINE_SHUT_DOWN, SESSION_NOT_FOUND, HANDLE_NOT_FOUND, VARIANT_NOT_FOUND, STREAM_NOT_FOUND, INTERACTION_INVALID, CONTRACT_INVALID, CONTRACT_VERSION_UNSUPPORTED, VARIANT_BUDGET_EXCEEDED, COMPONENT_UNAVAILABLE, COMPONENT_FAILED, INTERNAL);
  }

  /** Known values of {@code Event.kind}. */
  public static final class EventKind {
    private EventKind() {}

    public static final String VERIFICATION_STARTED = "verification/started";
    public static final String VERIFICATION_INTERACTION_STARTED = "verification/interaction-started";
    public static final String VERIFICATION_INTERACTION_RESULT = "verification/interaction-result";
    public static final String VERIFICATION_HOOK = "verification/hook";
    public static final String VERIFICATION_EXECUTED_PLAN = "verification/executed-plan";
    public static final String VERIFICATION_FINISHED = "verification/finished";

    public static final List<String> KNOWN = List.of(VERIFICATION_STARTED, VERIFICATION_INTERACTION_STARTED, VERIFICATION_INTERACTION_RESULT, VERIFICATION_HOOK, VERIFICATION_EXECUTED_PLAN, VERIFICATION_FINISHED);
  }

  /** Known values of {@code ExplainSubject.kind}. */
  public static final class ExplainSubjectKind {
    private ExplainSubjectKind() {}

    public static final String SPEC = "spec";
    public static final String CONTRACT_INTERACTION = "contract-interaction";

    public static final List<String> KNOWN = List.of(SPEC, CONTRACT_INTERACTION);
  }

  /** Known values of {@code Frame.type}. */
  public static final class FrameType {
    private FrameType() {}

    public static final String REQUEST = "request";
    public static final String RESPONSE = "response";
    public static final String EVENT = "event";

    public static final List<String> KNOWN = List.of(REQUEST, RESPONSE, EVENT);
  }

  /** Known values of {@code InteractionResult.status}. */
  public static final class InteractionResultStatus {
    private InteractionResultStatus() {}

    public static final String VERIFIED = "verified";
    public static final String FAILED = "failed";
    public static final String NOT_EXERCISED = "not-exercised";

    public static final List<String> KNOWN = List.of(VERIFIED, FAILED, NOT_EXERCISED);
  }

  /** Known values of {@code RequestFrame.op}. */
  public static final class RequestFrameOp {
    private RequestFrameOp() {}

    public static final String ENGINE_HELLO = "engine/hello";
    public static final String ENGINE_SHUTDOWN = "engine/shutdown";
    public static final String CONSUMER_SESSION_CREATE = "consumer-session/create";
    public static final String CONSUMER_SESSION_ADD_INTERACTION = "consumer-session/add-interaction";
    public static final String CONSUMER_SESSION_VARIANTS = "consumer-session/variants";
    public static final String CONSUMER_SESSION_START_TRANSPORT = "consumer-session/start-transport";
    public static final String CONSUMER_SESSION_SERVE_VARIANT = "consumer-session/serve-variant";
    public static final String CONSUMER_SESSION_FINALISE = "consumer-session/finalise";
    public static final String VERIFICATION_VERIFY = "verification/verify";
    public static final String VERIFICATION_EXPLAIN = "verification/explain";
    public static final String UPGRADE_PACT = "upgrade/pact";
    public static final String EVENTS_POLL = "events/poll";

    public static final List<String> KNOWN = List.of(ENGINE_HELLO, ENGINE_SHUTDOWN, CONSUMER_SESSION_CREATE, CONSUMER_SESSION_ADD_INTERACTION, CONSUMER_SESSION_VARIANTS, CONSUMER_SESSION_START_TRANSPORT, CONSUMER_SESSION_SERVE_VARIANT, CONSUMER_SESSION_FINALISE, VERIFICATION_VERIFY, VERIFICATION_EXPLAIN, UPGRADE_PACT, EVENTS_POLL);
  }

  /** Known values of {@code StartTransport.transport}. */
  public static final class StartTransportTransport {
    private StartTransportTransport() {}

    public static final String HTTP = "http";

    public static final List<String> KNOWN = List.of(HTTP);
  }

  /** Known values of {@code TransportBinding.transport}. */
  public static final class TransportBindingTransport {
    private TransportBindingTransport() {}

    public static final String HTTP = "http";

    public static final List<String> KNOWN = List.of(HTTP);
  }

  /** Known values of {@code UpgradeFinding.code}. */
  public static final class UpgradeFindingCode {
    private UpgradeFindingCode() {}

    public static final String EXAMPLE_FROZEN_AS_EQUALITY = "example-frozen-as-equality";
    public static final String RULE_UNMAPPED = "rule-unmapped";
    public static final String RULE_COMBINATION_OR = "rule-combination-or";
    public static final String RULE_NARROWED = "rule-narrowed";
    public static final String GENERATOR_DROPPED = "generator-dropped";
    public static final String CONTENT_TYPE_INFERRED = "content-type-inferred";
    public static final String BODY_NOT_PARSED = "body-not-parsed";
    public static final String STATE_PARAMS_UNTYPED = "state-params-untyped";
    public static final String DUPLICATE_DESCRIPTION = "duplicate-description";
    public static final String INTERACTION_DROPPED = "interaction-dropped";

    public static final List<String> KNOWN = List.of(EXAMPLE_FROZEN_AS_EQUALITY, RULE_UNMAPPED, RULE_COMBINATION_OR, RULE_NARROWED, GENERATOR_DROPPED, CONTENT_TYPE_INFERRED, BODY_NOT_PARSED, STATE_PARAMS_UNTYPED, DUPLICATE_DESCRIPTION, INTERACTION_DROPPED);
  }

  /** Known values of {@code UpgradeFinding.kind}. */
  public static final class UpgradeFindingKind {
    private UpgradeFindingKind() {}

    public static final String LOSSY = "lossy";
    public static final String JUDGEMENT = "judgement";
    public static final String NOTE = "note";

    public static final List<String> KNOWN = List.of(LOSSY, JUDGEMENT, NOTE);
  }

  /** Known values of {@code VariantResult.status}. */
  public static final class VariantResultStatus {
    private VariantResultStatus() {}

    public static final String VERIFIED = "verified";
    public static final String FAILED = "failed";
    public static final String NOT_EXERCISED = "not-exercised";

    public static final List<String> KNOWN = List.of(VERIFIED, FAILED, NOT_EXERCISED);
  }
}
