/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Contract
 * <p>
 * A Janus contract: what a consumer demonstrated against a mock, recorded so a provider can be held to it (spec.md §2). Not a pact file — ADR 0011 names this its own format. Documents this schema treats as opaque objects are owned elsewhere and validated against their own schemas: shapes by design 2.2, the selection report by design 2.3, transport and endpoint descriptors by design 2.6.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "$format",
    "$schema",
    "consumer",
    "interactions",
    "metadata",
    "provider"
})
public class Contract {

    /**
     * The format token. A writer MUST emit this as the document's first member, so a conformant file begins with the byte prefix '{"$format":' (spec.md §2.3). JSON Schema cannot express member order; the writer conformance test does.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    @JsonPropertyDescription("The format token. A writer MUST emit this as the document's first member, so a conformant file begins with the byte prefix '{\"$format\":' (spec.md \u00a72.3). JSON Schema cannot express member order; the writer conformance test does.")
    private String $format;
    /**
     * Advisory: the schema this document claims to follow. Identifier only — a reader MUST NOT fetch it (spec.md §2.3).
     * 
     */
    @JsonProperty("$schema")
    @JsonPropertyDescription("Advisory: the schema this document claims to follow. Identifier only \u2014 a reader MUST NOT fetch it (spec.md \u00a72.3).")
    private String $schema;
    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    @JsonPropertyDescription("A named party. The member name and the path to 'name' are fixed by spec.md \u00a73.1 so brokers already deployed read them correctly.")
    private Party consumer;
    /**
     * In the order the consumer submitted them. Every interaction here was exercised successfully on every variant its selection required (spec.md §2.2) — a contract is never written otherwise.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    @JsonPropertyDescription("In the order the consumer submitted them. Every interaction here was exercised successfully on every variant its selection required (spec.md \u00a72.2) \u2014 a contract is never written otherwise.")
    private List<Interaction> interactions;
    /**
     * Metadata
     * <p>
     * How the file came to exist, and nothing that changes what a verifier does (spec.md §3.2). Deliberately outside the content-addressed identity, so an unchanged rebuild is not a new contract. MUST NOT carry 'pactSpecification' — a Janus contract conforms to no pact specification version (ADR 0011).
     * 
     */
    @JsonProperty("metadata")
    @JsonPropertyDescription("How the file came to exist, and nothing that changes what a verifier does (spec.md \u00a73.2). Deliberately outside the content-addressed identity, so an unchanged rebuild is not a new contract. MUST NOT carry 'pactSpecification' \u2014 a Janus contract conforms to no pact specification version (ADR 0011).")
    private Metadata metadata;
    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("provider")
    @JsonPropertyDescription("A named party. The member name and the path to 'name' are fixed by spec.md \u00a73.1 so brokers already deployed read them correctly.")
    private Party provider;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * The format token. A writer MUST emit this as the document's first member, so a conformant file begins with the byte prefix '{"$format":' (spec.md §2.3). JSON Schema cannot express member order; the writer conformance test does.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    public String get$format() {
        return $format;
    }

    /**
     * The format token. A writer MUST emit this as the document's first member, so a conformant file begins with the byte prefix '{"$format":' (spec.md §2.3). JSON Schema cannot express member order; the writer conformance test does.
     * (Required)
     * 
     */
    @JsonProperty("$format")
    public void set$format(String $format) {
        this.$format = $format;
    }

    /**
     * Advisory: the schema this document claims to follow. Identifier only — a reader MUST NOT fetch it (spec.md §2.3).
     * 
     */
    @JsonProperty("$schema")
    public String get$schema() {
        return $schema;
    }

    /**
     * Advisory: the schema this document claims to follow. Identifier only — a reader MUST NOT fetch it (spec.md §2.3).
     * 
     */
    @JsonProperty("$schema")
    public void set$schema(String $schema) {
        this.$schema = $schema;
    }

    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    public Party getConsumer() {
        return consumer;
    }

    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("consumer")
    public void setConsumer(Party consumer) {
        this.consumer = consumer;
    }

    /**
     * In the order the consumer submitted them. Every interaction here was exercised successfully on every variant its selection required (spec.md §2.2) — a contract is never written otherwise.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public List<Interaction> getInteractions() {
        return interactions;
    }

    /**
     * In the order the consumer submitted them. Every interaction here was exercised successfully on every variant its selection required (spec.md §2.2) — a contract is never written otherwise.
     * (Required)
     * 
     */
    @JsonProperty("interactions")
    public void setInteractions(List<Interaction> interactions) {
        this.interactions = interactions;
    }

    /**
     * Metadata
     * <p>
     * How the file came to exist, and nothing that changes what a verifier does (spec.md §3.2). Deliberately outside the content-addressed identity, so an unchanged rebuild is not a new contract. MUST NOT carry 'pactSpecification' — a Janus contract conforms to no pact specification version (ADR 0011).
     * 
     */
    @JsonProperty("metadata")
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Metadata
     * <p>
     * How the file came to exist, and nothing that changes what a verifier does (spec.md §3.2). Deliberately outside the content-addressed identity, so an unchanged rebuild is not a new contract. MUST NOT carry 'pactSpecification' — a Janus contract conforms to no pact specification version (ADR 0011).
     * 
     */
    @JsonProperty("metadata")
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("provider")
    public Party getProvider() {
        return provider;
    }

    /**
     * Party
     * <p>
     * A named party. The member name and the path to 'name' are fixed by spec.md §3.1 so brokers already deployed read them correctly.
     * (Required)
     * 
     */
    @JsonProperty("provider")
    public void setProvider(Party provider) {
        this.provider = provider;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Contract.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("$format");
        sb.append('=');
        sb.append(((this.$format == null)?"<null>":this.$format));
        sb.append(',');
        sb.append("$schema");
        sb.append('=');
        sb.append(((this.$schema == null)?"<null>":this.$schema));
        sb.append(',');
        sb.append("consumer");
        sb.append('=');
        sb.append(((this.consumer == null)?"<null>":this.consumer));
        sb.append(',');
        sb.append("interactions");
        sb.append('=');
        sb.append(((this.interactions == null)?"<null>":this.interactions));
        sb.append(',');
        sb.append("metadata");
        sb.append('=');
        sb.append(((this.metadata == null)?"<null>":this.metadata));
        sb.append(',');
        sb.append("provider");
        sb.append('=');
        sb.append(((this.provider == null)?"<null>":this.provider));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.metadata == null)? 0 :this.metadata.hashCode()));
        result = ((result* 31)+((this.$schema == null)? 0 :this.$schema.hashCode()));
        result = ((result* 31)+((this.provider == null)? 0 :this.provider.hashCode()));
        result = ((result* 31)+((this.$format == null)? 0 :this.$format.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.consumer == null)? 0 :this.consumer.hashCode()));
        result = ((result* 31)+((this.interactions == null)? 0 :this.interactions.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Contract) == false) {
            return false;
        }
        Contract rhs = ((Contract) other);
        return ((((((((this.metadata == rhs.metadata)||((this.metadata!= null)&&this.metadata.equals(rhs.metadata)))&&((this.$schema == rhs.$schema)||((this.$schema!= null)&&this.$schema.equals(rhs.$schema))))&&((this.provider == rhs.provider)||((this.provider!= null)&&this.provider.equals(rhs.provider))))&&((this.$format == rhs.$format)||((this.$format!= null)&&this.$format.equals(rhs.$format))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.consumer == rhs.consumer)||((this.consumer!= null)&&this.consumer.equals(rhs.consumer))))&&((this.interactions == rhs.interactions)||((this.interactions!= null)&&this.interactions.equals(rhs.interactions))));
    }

}
