/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * InteractionSpec
 * <p>
 * The interaction specification an author writes and a host submits to 'consumer-session/add-interaction': this document's interaction record minus the evidence — the same members as 'Interaction', with no 'selection' (spec.md §1). Not a member of a contract; it is defined here so the author's input and the engine's output stay one document with one optional half.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "content-types",
    "description",
    "parts",
    "requires",
    "states",
    "transport"
})
public class InteractionSpec {

    /**
     * ContentTypes
     * <p>
     * Part name -> slot name -> the media type of that slot's content (spec.md §5.5, ADR 0020). A decode instruction, not a constraint: it names the content component that turns the slot's octets into the document its shape applies to, and back. Absent for a slot means an undeclared one: produced as JSON when structured, decoded as the arriving slot is labelled. Every entry must name a slot 'parts' gives a shape.
     * 
     */
    @JsonProperty("content-types")
    @JsonPropertyDescription("Part name -> slot name -> the media type of that slot's content (spec.md \u00a75.5, ADR 0020). A decode instruction, not a constraint: it names the content component that turns the slot's octets into the document its shape applies to, and back. Absent for a slot means an undeclared one: produced as JSON when structured, decoded as the arriving slot is labelled. Every entry must name a slot 'parts' gives a shape.")
    private ContentTypes contentTypes;
    /**
     * What the interaction is, in the author's words (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    @JsonPropertyDescription("What the interaction is, in the author's words (spec.md \u00a74.2).")
    private java.lang.String description;
    /**
     * Part name -> slot name -> shape (shape spec §3.6).
     * (Required)
     * 
     */
    @JsonProperty("parts")
    @JsonPropertyDescription("Part name -> slot name -> shape (shape spec \u00a73.6).")
    private Map<String, ShapePart> parts;
    /**
     * Components this interaction cannot be matched without (spec.md §7).
     * 
     */
    @JsonProperty("requires")
    @JsonPropertyDescription("Components this interaction cannot be matched without (spec.md \u00a77).")
    private List<Requirement> requires;
    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6).
     * 
     */
    @JsonProperty("states")
    @JsonPropertyDescription("Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md \u00a76).")
    private List<State> states;
    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    @JsonPropertyDescription("How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).")
    private Transport transport;
    @JsonIgnore
    private Map<java.lang.String, Object> additionalProperties = new LinkedHashMap<java.lang.String, Object>();

    /**
     * ContentTypes
     * <p>
     * Part name -> slot name -> the media type of that slot's content (spec.md §5.5, ADR 0020). A decode instruction, not a constraint: it names the content component that turns the slot's octets into the document its shape applies to, and back. Absent for a slot means an undeclared one: produced as JSON when structured, decoded as the arriving slot is labelled. Every entry must name a slot 'parts' gives a shape.
     * 
     */
    @JsonProperty("content-types")
    public ContentTypes getContentTypes() {
        return contentTypes;
    }

    /**
     * ContentTypes
     * <p>
     * Part name -> slot name -> the media type of that slot's content (spec.md §5.5, ADR 0020). A decode instruction, not a constraint: it names the content component that turns the slot's octets into the document its shape applies to, and back. Absent for a slot means an undeclared one: produced as JSON when structured, decoded as the arriving slot is labelled. Every entry must name a slot 'parts' gives a shape.
     * 
     */
    @JsonProperty("content-types")
    public void setContentTypes(ContentTypes contentTypes) {
        this.contentTypes = contentTypes;
    }

    /**
     * What the interaction is, in the author's words (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    public java.lang.String getDescription() {
        return description;
    }

    /**
     * What the interaction is, in the author's words (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     * Part name -> slot name -> shape (shape spec §3.6).
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public Map<String, ShapePart> getParts() {
        return parts;
    }

    /**
     * Part name -> slot name -> shape (shape spec §3.6).
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public void setParts(Map<String, ShapePart> parts) {
        this.parts = parts;
    }

    /**
     * Components this interaction cannot be matched without (spec.md §7).
     * 
     */
    @JsonProperty("requires")
    public List<Requirement> getRequires() {
        return requires;
    }

    /**
     * Components this interaction cannot be matched without (spec.md §7).
     * 
     */
    @JsonProperty("requires")
    public void setRequires(List<Requirement> requires) {
        this.requires = requires;
    }

    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6).
     * 
     */
    @JsonProperty("states")
    public List<State> getStates() {
        return states;
    }

    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6).
     * 
     */
    @JsonProperty("states")
    public void setStates(List<State> states) {
        this.states = states;
    }

    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    public Transport getTransport() {
        return transport;
    }

    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    public void setTransport(Transport transport) {
        this.transport = transport;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(InteractionSpec.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("contentTypes");
        sb.append('=');
        sb.append(((this.contentTypes == null)?"<null>":this.contentTypes));
        sb.append(',');
        sb.append("description");
        sb.append('=');
        sb.append(((this.description == null)?"<null>":this.description));
        sb.append(',');
        sb.append("parts");
        sb.append('=');
        sb.append(((this.parts == null)?"<null>":this.parts));
        sb.append(',');
        sb.append("requires");
        sb.append('=');
        sb.append(((this.requires == null)?"<null>":this.requires));
        sb.append(',');
        sb.append("states");
        sb.append('=');
        sb.append(((this.states == null)?"<null>":this.states));
        sb.append(',');
        sb.append("transport");
        sb.append('=');
        sb.append(((this.transport == null)?"<null>":this.transport));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.parts == null)? 0 :this.parts.hashCode()));
        result = ((result* 31)+((this.description == null)? 0 :this.description.hashCode()));
        result = ((result* 31)+((this.transport == null)? 0 :this.transport.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.contentTypes == null)? 0 :this.contentTypes.hashCode()));
        result = ((result* 31)+((this.requires == null)? 0 :this.requires.hashCode()));
        result = ((result* 31)+((this.states == null)? 0 :this.states.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof InteractionSpec) == false) {
            return false;
        }
        InteractionSpec rhs = ((InteractionSpec) other);
        return ((((((((this.parts == rhs.parts)||((this.parts!= null)&&this.parts.equals(rhs.parts)))&&((this.description == rhs.description)||((this.description!= null)&&this.description.equals(rhs.description))))&&((this.transport == rhs.transport)||((this.transport!= null)&&this.transport.equals(rhs.transport))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.contentTypes == rhs.contentTypes)||((this.contentTypes!= null)&&this.contentTypes.equals(rhs.contentTypes))))&&((this.requires == rhs.requires)||((this.requires!= null)&&this.requires.equals(rhs.requires))))&&((this.states == rhs.states)||((this.states!= null)&&this.states.equals(rhs.states))));
    }

}
