/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Interaction
 * <p>
 * One interaction: its shape recorded once, and the evidence of every variant that was exercised (spec.md §4). Identity is 'description' plus 'states' (spec.md §4.2).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "description",
    "parts",
    "requires",
    "selection",
    "states",
    "transport"
})
public class Interaction {

    /**
     * What the interaction is, in the author's words. Unique within a contract for a given state list (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    @JsonPropertyDescription("What the interaction is, in the author's words. Unique within a contract for a given state list (spec.md \u00a74.2).")
    private java.lang.String description;
    /**
     * Part name -> slot name -> shape. Part and slot names are the transport and content components' business, never the kernel's (shape spec §3.6); this schema fixes only the nesting.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    @JsonPropertyDescription("Part name -> slot name -> shape. Part and slot names are the transport and content components' business, never the kernel's (shape spec \u00a73.6); this schema fixes only the nesting.")
    private Map<String, ShapePart> parts;
    /**
     * Components this interaction cannot be matched without (spec.md §7). A verifier collects the union across interactions before it starts.
     * 
     */
    @JsonProperty("requires")
    @JsonPropertyDescription("Components this interaction cannot be matched without (spec.md \u00a77). A verifier collects the union across interactions before it starts.")
    private List<Requirement> requires;
    /**
     * RecordedSelection
     * <p>
     * Design 2.3's variant-selection document — the exercised variants and the report of how they were chosen — with the evidence this design adds. Members not named here belong to variant-selection.schema.json and are validated against it (spec.md §5.1).
     * (Required)
     * 
     */
    @JsonProperty("selection")
    @JsonPropertyDescription("Design 2.3's variant-selection document \u2014 the exercised variants and the report of how they were chosen \u2014 with the evidence this design adds. Members not named here belong to variant-selection.schema.json and are validated against it (spec.md \u00a75.1).")
    private RecordedSelection selection;
    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6). Bindings appear here once; their resolved values appear per variant.
     * 
     */
    @JsonProperty("states")
    @JsonPropertyDescription("Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md \u00a76). Bindings appear here once; their resolved values appear per variant.")
    private List<State> states;
    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    @JsonPropertyDescription("How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).")
    private Transport transport;
    @JsonIgnore
    private Map<java.lang.String, Object> additionalProperties = new LinkedHashMap<java.lang.String, Object>();

    /**
     * What the interaction is, in the author's words. Unique within a contract for a given state list (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    public java.lang.String getDescription() {
        return description;
    }

    /**
     * What the interaction is, in the author's words. Unique within a contract for a given state list (spec.md §4.2).
     * (Required)
     * 
     */
    @JsonProperty("description")
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     * Part name -> slot name -> shape. Part and slot names are the transport and content components' business, never the kernel's (shape spec §3.6); this schema fixes only the nesting.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public Map<String, ShapePart> getParts() {
        return parts;
    }

    /**
     * Part name -> slot name -> shape. Part and slot names are the transport and content components' business, never the kernel's (shape spec §3.6); this schema fixes only the nesting.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public void setParts(Map<String, ShapePart> parts) {
        this.parts = parts;
    }

    /**
     * Components this interaction cannot be matched without (spec.md §7). A verifier collects the union across interactions before it starts.
     * 
     */
    @JsonProperty("requires")
    public List<Requirement> getRequires() {
        return requires;
    }

    /**
     * Components this interaction cannot be matched without (spec.md §7). A verifier collects the union across interactions before it starts.
     * 
     */
    @JsonProperty("requires")
    public void setRequires(List<Requirement> requires) {
        this.requires = requires;
    }

    /**
     * RecordedSelection
     * <p>
     * Design 2.3's variant-selection document — the exercised variants and the report of how they were chosen — with the evidence this design adds. Members not named here belong to variant-selection.schema.json and are validated against it (spec.md §5.1).
     * (Required)
     * 
     */
    @JsonProperty("selection")
    public RecordedSelection getSelection() {
        return selection;
    }

    /**
     * RecordedSelection
     * <p>
     * Design 2.3's variant-selection document — the exercised variants and the report of how they were chosen — with the evidence this design adds. Members not named here belong to variant-selection.schema.json and are validated against it (spec.md §5.1).
     * (Required)
     * 
     */
    @JsonProperty("selection")
    public void setSelection(RecordedSelection selection) {
        this.selection = selection;
    }

    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6). Bindings appear here once; their resolved values appear per variant.
     * 
     */
    @JsonProperty("states")
    public List<State> getStates() {
        return states;
    }

    /**
     * Provider states this interaction requires, with their literal parameters and their variant bindings (spec.md §6). Bindings appear here once; their resolved values appear per variant.
     * 
     */
    @JsonProperty("states")
    public void setStates(List<State> states) {
        this.states = states;
    }

    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    public Transport getTransport() {
        return transport;
    }

    /**
     * Transport
     * <p>
     * How the parts crossed the wire. An open descriptor: 'kind' and 'mode' are fixed here, everything else belongs to the transport component (design 2.6).
     * 
     */
    @JsonProperty("transport")
    public void setTransport(Transport transport) {
        this.transport = transport;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Interaction.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("description");
        sb.append('=');
        sb.append(((this.description == null)?"<null>":this.description));
        sb.append(',');
        sb.append("parts");
        sb.append('=');
        sb.append(((this.parts == null)?"<null>":this.parts));
        sb.append(',');
        sb.append("requires");
        sb.append('=');
        sb.append(((this.requires == null)?"<null>":this.requires));
        sb.append(',');
        sb.append("selection");
        sb.append('=');
        sb.append(((this.selection == null)?"<null>":this.selection));
        sb.append(',');
        sb.append("states");
        sb.append('=');
        sb.append(((this.states == null)?"<null>":this.states));
        sb.append(',');
        sb.append("transport");
        sb.append('=');
        sb.append(((this.transport == null)?"<null>":this.transport));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.selection == null)? 0 :this.selection.hashCode()));
        result = ((result* 31)+((this.parts == null)? 0 :this.parts.hashCode()));
        result = ((result* 31)+((this.description == null)? 0 :this.description.hashCode()));
        result = ((result* 31)+((this.transport == null)? 0 :this.transport.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.requires == null)? 0 :this.requires.hashCode()));
        result = ((result* 31)+((this.states == null)? 0 :this.states.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Interaction) == false) {
            return false;
        }
        Interaction rhs = ((Interaction) other);
        return ((((((((this.selection == rhs.selection)||((this.selection!= null)&&this.selection.equals(rhs.selection)))&&((this.parts == rhs.parts)||((this.parts!= null)&&this.parts.equals(rhs.parts))))&&((this.description == rhs.description)||((this.description!= null)&&this.description.equals(rhs.description))))&&((this.transport == rhs.transport)||((this.transport!= null)&&this.transport.equals(rhs.transport))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.requires == rhs.requires)||((this.requires!= null)&&this.requires.equals(rhs.requires))))&&((this.states == rhs.states)||((this.states!= null)&&this.states.equals(rhs.states))));
    }

}
