/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RecordedVariant
 * <p>
 * One exercised variant: its identity from design 2.3, and the concrete values it produced. 'parts' is this design's addition to design 2.3's variant document (variant semantics §4.4).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "assignment",
    "id",
    "parts",
    "states"
})
public class RecordedVariant {

    /**
     * The assignment is the truth and the id is its name; both are recorded so a variant stays interpretable against a shape that has since grown a dimension.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    @JsonPropertyDescription("The assignment is the truth and the id is its name; both are recorded so a variant stays interpretable against a shape that has since grown a dimension.")
    private List<Map<String, Object>> assignment;
    /**
     * The variant id. 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default. Never a label (variant semantics §2.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    @JsonPropertyDescription("The variant id. 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default. Never a label (variant semantics \u00a72.2).")
    private java.lang.String id;
    /**
     * Part name -> slot name -> the concrete value produced. Keyed identically to the interaction's 'parts', so shape and evidence line up slot for slot.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    @JsonPropertyDescription("Part name -> slot name -> the concrete value produced. Keyed identically to the interaction's 'parts', so shape and evidence line up slot for slot.")
    private Map<String, ValuePart> parts;
    /**
     * The interaction's states with this variant's parameters resolved (variant semantics §6.4). Resolved values only — bindings live on the interaction, never here.
     * 
     */
    @JsonProperty("states")
    @JsonPropertyDescription("The interaction's states with this variant's parameters resolved (variant semantics \u00a76.4). Resolved values only \u2014 bindings live on the interaction, never here.")
    private List<ResolvedState> states;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * The assignment is the truth and the id is its name; both are recorded so a variant stays interpretable against a shape that has since grown a dimension.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    public List<Map<String, Object>> getAssignment() {
        return assignment;
    }

    /**
     * The assignment is the truth and the id is its name; both are recorded so a variant stays interpretable against a shape that has since grown a dimension.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    public void setAssignment(List<Map<String, Object>> assignment) {
        this.assignment = assignment;
    }

    /**
     * The variant id. 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default. Never a label (variant semantics §2.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    public java.lang.String getId() {
        return id;
    }

    /**
     * The variant id. 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default. Never a label (variant semantics §2.2).
     * (Required)
     * 
     */
    @JsonProperty("id")
    public void setId(java.lang.String id) {
        this.id = id;
    }

    /**
     * Part name -> slot name -> the concrete value produced. Keyed identically to the interaction's 'parts', so shape and evidence line up slot for slot.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public Map<String, ValuePart> getParts() {
        return parts;
    }

    /**
     * Part name -> slot name -> the concrete value produced. Keyed identically to the interaction's 'parts', so shape and evidence line up slot for slot.
     * (Required)
     * 
     */
    @JsonProperty("parts")
    public void setParts(Map<String, ValuePart> parts) {
        this.parts = parts;
    }

    /**
     * The interaction's states with this variant's parameters resolved (variant semantics §6.4). Resolved values only — bindings live on the interaction, never here.
     * 
     */
    @JsonProperty("states")
    public List<ResolvedState> getStates() {
        return states;
    }

    /**
     * The interaction's states with this variant's parameters resolved (variant semantics §6.4). Resolved values only — bindings live on the interaction, never here.
     * 
     */
    @JsonProperty("states")
    public void setStates(List<ResolvedState> states) {
        this.states = states;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(RecordedVariant.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("assignment");
        sb.append('=');
        sb.append(((this.assignment == null)?"<null>":this.assignment));
        sb.append(',');
        sb.append("id");
        sb.append('=');
        sb.append(((this.id == null)?"<null>":this.id));
        sb.append(',');
        sb.append("parts");
        sb.append('=');
        sb.append(((this.parts == null)?"<null>":this.parts));
        sb.append(',');
        sb.append("states");
        sb.append('=');
        sb.append(((this.states == null)?"<null>":this.states));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.parts == null)? 0 :this.parts.hashCode()));
        result = ((result* 31)+((this.id == null)? 0 :this.id.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.assignment == null)? 0 :this.assignment.hashCode()));
        result = ((result* 31)+((this.states == null)? 0 :this.states.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof RecordedVariant) == false) {
            return false;
        }
        RecordedVariant rhs = ((RecordedVariant) other);
        return ((((((this.parts == rhs.parts)||((this.parts!= null)&&this.parts.equals(rhs.parts)))&&((this.id == rhs.id)||((this.id!= null)&&this.id.equals(rhs.id))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.assignment == rhs.assignment)||((this.assignment!= null)&&this.assignment.equals(rhs.assignment))))&&((this.states == rhs.states)||((this.states!= null)&&this.states.equals(rhs.states))));
    }

}
