/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * RecordedSelection
 * <p>
 * Design 2.3's variant-selection document — the exercised variants and the report of how they were chosen — with the evidence this design adds. Members not named here belong to variant-selection.schema.json and are validated against it (spec.md §5.1).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "report",
    "variants"
})
public class RecordedSelection {

    /**
     * Design 2.3's selection report. Recording it is what makes a contract self-describing about its own coverage.
     * (Required)
     * 
     */
    @JsonProperty("report")
    @JsonPropertyDescription("Design 2.3's selection report. Recording it is what makes a contract self-describing about its own coverage.")
    private Map<String, Object> report;
    /**
     * In recorded order, which is run order: a verifier replays exactly these, in this order, and never re-samples (variant semantics §5.1). Only exercised variants appear — the honesty rule.
     * (Required)
     * 
     */
    @JsonProperty("variants")
    @JsonPropertyDescription("In recorded order, which is run order: a verifier replays exactly these, in this order, and never re-samples (variant semantics \u00a75.1). Only exercised variants appear \u2014 the honesty rule.")
    private List<RecordedVariant> variants;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * Design 2.3's selection report. Recording it is what makes a contract self-describing about its own coverage.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public Map<String, Object> getReport() {
        return report;
    }

    /**
     * Design 2.3's selection report. Recording it is what makes a contract self-describing about its own coverage.
     * (Required)
     * 
     */
    @JsonProperty("report")
    public void setReport(Map<String, Object> report) {
        this.report = report;
    }

    /**
     * In recorded order, which is run order: a verifier replays exactly these, in this order, and never re-samples (variant semantics §5.1). Only exercised variants appear — the honesty rule.
     * (Required)
     * 
     */
    @JsonProperty("variants")
    public List<RecordedVariant> getVariants() {
        return variants;
    }

    /**
     * In recorded order, which is run order: a verifier replays exactly these, in this order, and never re-samples (variant semantics §5.1). Only exercised variants appear — the honesty rule.
     * (Required)
     * 
     */
    @JsonProperty("variants")
    public void setVariants(List<RecordedVariant> variants) {
        this.variants = variants;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(RecordedSelection.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("report");
        sb.append('=');
        sb.append(((this.report == null)?"<null>":this.report));
        sb.append(',');
        sb.append("variants");
        sb.append('=');
        sb.append(((this.variants == null)?"<null>":this.variants));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.report == null)? 0 :this.report.hashCode()));
        result = ((result* 31)+((this.variants == null)? 0 :this.variants.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof RecordedSelection) == false) {
            return false;
        }
        RecordedSelection rhs = ((RecordedSelection) other);
        return ((((this.report == rhs.report)||((this.report!= null)&&this.report.equals(rhs.report)))&&((this.variants == rhs.variants)||((this.variants!= null)&&this.variants.equals(rhs.variants))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
