/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Requirement
 * <p>
 * A component the interaction needs, at a major version or above (spec.md §7). Structured rather than an expression string, because a document that must be evaluated to be understood cannot be reviewed (ADR 0007's reasoning).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "component",
    "min-version"
})
public class Requirement {

    /**
     * '<interface>/<name>', e.g. 'content/protobuf'. The interface half is an open vocabulary owned by design 2.6.
     * (Required)
     * 
     */
    @JsonProperty("component")
    @JsonPropertyDescription("'<interface>/<name>', e.g. 'content/protobuf'. The interface half is an open vocabulary owned by design 2.6.")
    private String component;
    /**
     * Lowest acceptable major version. Majors only: the protocol is coarse-grained by ADR 0002, and a contract that pins a patch is a contract that breaks on a bug fix.
     * 
     */
    @JsonProperty("min-version")
    @JsonPropertyDescription("Lowest acceptable major version. Majors only: the protocol is coarse-grained by ADR 0002, and a contract that pins a patch is a contract that breaks on a bug fix.")
    private Long minVersion;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * '<interface>/<name>', e.g. 'content/protobuf'. The interface half is an open vocabulary owned by design 2.6.
     * (Required)
     * 
     */
    @JsonProperty("component")
    public String getComponent() {
        return component;
    }

    /**
     * '<interface>/<name>', e.g. 'content/protobuf'. The interface half is an open vocabulary owned by design 2.6.
     * (Required)
     * 
     */
    @JsonProperty("component")
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * Lowest acceptable major version. Majors only: the protocol is coarse-grained by ADR 0002, and a contract that pins a patch is a contract that breaks on a bug fix.
     * 
     */
    @JsonProperty("min-version")
    public Long getMinVersion() {
        return minVersion;
    }

    /**
     * Lowest acceptable major version. Majors only: the protocol is coarse-grained by ADR 0002, and a contract that pins a patch is a contract that breaks on a bug fix.
     * 
     */
    @JsonProperty("min-version")
    public void setMinVersion(Long minVersion) {
        this.minVersion = minVersion;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Requirement.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("component");
        sb.append('=');
        sb.append(((this.component == null)?"<null>":this.component));
        sb.append(',');
        sb.append("minVersion");
        sb.append('=');
        sb.append(((this.minVersion == null)?"<null>":this.minVersion));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.component == null)? 0 :this.component.hashCode()));
        result = ((result* 31)+((this.minVersion == null)? 0 :this.minVersion.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Requirement) == false) {
            return false;
        }
        Requirement rhs = ((Requirement) other);
        return ((((this.component == rhs.component)||((this.component!= null)&&this.component.equals(rhs.component)))&&((this.minVersion == rhs.minVersion)||((this.minVersion!= null)&&this.minVersion.equals(rhs.minVersion))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
