/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SlotValue
 * <p>
 * The value a slot carried, always wrapped. The wrapper is unconditional and never in-band: a bare value with a sibling tag would be ambiguous against user data that happens to have that member, which is the trap ADR 0007 and variant semantics §6.2 both refuse (spec.md §5.3).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "content",
    "content-type",
    "encoded"
})
public class SlotValue {

    /**
     * The value, represented as 'encoded' says. Absent means the slot was empty; null means the slot carried a null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    @JsonPropertyDescription("The value, represented as 'encoded' says. Absent means the slot was empty; null means the slot carried a null.")
    private Object content;
    /**
     * The media type the part declared for this slot, when it had one. Recorded because a verifier hands it to the content component and must not re-derive it.
     * 
     */
    @JsonProperty("content-type")
    @JsonPropertyDescription("The media type the part declared for this slot, when it had one. Recorded because a verifier hands it to the content component and must not re-derive it.")
    private String contentType;
    /**
     * How to read 'content': 'json' is the value as it stands, so a JSON body stays readable and addressable; 'text' is a string whose octets are its UTF-8 encoding; 'base64' is RFC 4648 §4 octets (ADR 0006).
     * 
     */
    @JsonProperty("encoded")
    @JsonPropertyDescription("How to read 'content': 'json' is the value as it stands, so a JSON body stays readable and addressable; 'text' is a string whose octets are its UTF-8 encoding; 'base64' is RFC 4648 \u00a74 octets (ADR 0006).")
    private String encoded;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * The value, represented as 'encoded' says. Absent means the slot was empty; null means the slot carried a null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    public Object getContent() {
        return content;
    }

    /**
     * The value, represented as 'encoded' says. Absent means the slot was empty; null means the slot carried a null.
     * (Required)
     * 
     */
    @JsonProperty("content")
    public void setContent(Object content) {
        this.content = content;
    }

    /**
     * The media type the part declared for this slot, when it had one. Recorded because a verifier hands it to the content component and must not re-derive it.
     * 
     */
    @JsonProperty("content-type")
    public String getContentType() {
        return contentType;
    }

    /**
     * The media type the part declared for this slot, when it had one. Recorded because a verifier hands it to the content component and must not re-derive it.
     * 
     */
    @JsonProperty("content-type")
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * How to read 'content': 'json' is the value as it stands, so a JSON body stays readable and addressable; 'text' is a string whose octets are its UTF-8 encoding; 'base64' is RFC 4648 §4 octets (ADR 0006).
     * 
     */
    @JsonProperty("encoded")
    public String getEncoded() {
        return encoded;
    }

    /**
     * How to read 'content': 'json' is the value as it stands, so a JSON body stays readable and addressable; 'text' is a string whose octets are its UTF-8 encoding; 'base64' is RFC 4648 §4 octets (ADR 0006).
     * 
     */
    @JsonProperty("encoded")
    public void setEncoded(String encoded) {
        this.encoded = encoded;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(SlotValue.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("content");
        sb.append('=');
        sb.append(((this.content == null)?"<null>":this.content));
        sb.append(',');
        sb.append("contentType");
        sb.append('=');
        sb.append(((this.contentType == null)?"<null>":this.contentType));
        sb.append(',');
        sb.append("encoded");
        sb.append('=');
        sb.append(((this.encoded == null)?"<null>":this.encoded));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.contentType == null)? 0 :this.contentType.hashCode()));
        result = ((result* 31)+((this.content == null)? 0 :this.content.hashCode()));
        result = ((result* 31)+((this.encoded == null)? 0 :this.encoded.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof SlotValue) == false) {
            return false;
        }
        SlotValue rhs = ((SlotValue) other);
        return (((((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties)))&&((this.contentType == rhs.contentType)||((this.contentType!= null)&&this.contentType.equals(rhs.contentType))))&&((this.content == rhs.content)||((this.content!= null)&&this.content.equals(rhs.content))))&&((this.encoded == rhs.encoded)||((this.encoded!= null)&&this.encoded.equals(rhs.encoded))));
    }

}
