/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * State
 * <p>
 * A provider state. 'params' holds literal parameters; 'variant-params' holds bindings whose value depends on the running variant (variant semantics §6.2, whose schema owns their contents).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "name",
    "params",
    "variant-params"
})
public class State {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("name")
    private java.lang.String name;
    /**
     * Literal parameters, as authored. A name appearing here MUST NOT also appear in 'variant-params' (variant semantics §6.2).
     * 
     */
    @JsonProperty("params")
    @JsonPropertyDescription("Literal parameters, as authored. A name appearing here MUST NOT also appear in 'variant-params' (variant semantics \u00a76.2).")
    private Map<String, Object> params;
    /**
     * Variant-bound parameter bindings. Each item is design 2.3's binding document; 'dimension' is always the resolved dimension id, never the author's shorthand (variant semantics §6.3).
     * 
     */
    @JsonProperty("variant-params")
    @JsonPropertyDescription("Variant-bound parameter bindings. Each item is design 2.3's binding document; 'dimension' is always the resolved dimension id, never the author's shorthand (variant semantics \u00a76.3).")
    private List<Map<String, Object>> variantParams;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("name")
    public java.lang.String getName() {
        return name;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("name")
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     * Literal parameters, as authored. A name appearing here MUST NOT also appear in 'variant-params' (variant semantics §6.2).
     * 
     */
    @JsonProperty("params")
    public Map<String, Object> getParams() {
        return params;
    }

    /**
     * Literal parameters, as authored. A name appearing here MUST NOT also appear in 'variant-params' (variant semantics §6.2).
     * 
     */
    @JsonProperty("params")
    public void setParams(Map<String, Object> params) {
        this.params = params;
    }

    /**
     * Variant-bound parameter bindings. Each item is design 2.3's binding document; 'dimension' is always the resolved dimension id, never the author's shorthand (variant semantics §6.3).
     * 
     */
    @JsonProperty("variant-params")
    public List<Map<String, Object>> getVariantParams() {
        return variantParams;
    }

    /**
     * Variant-bound parameter bindings. Each item is design 2.3's binding document; 'dimension' is always the resolved dimension id, never the author's shorthand (variant semantics §6.3).
     * 
     */
    @JsonProperty("variant-params")
    public void setVariantParams(List<Map<String, Object>> variantParams) {
        this.variantParams = variantParams;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(State.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("name");
        sb.append('=');
        sb.append(((this.name == null)?"<null>":this.name));
        sb.append(',');
        sb.append("params");
        sb.append('=');
        sb.append(((this.params == null)?"<null>":this.params));
        sb.append(',');
        sb.append("variantParams");
        sb.append('=');
        sb.append(((this.variantParams == null)?"<null>":this.variantParams));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.name == null)? 0 :this.name.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.params == null)? 0 :this.params.hashCode()));
        result = ((result* 31)+((this.variantParams == null)? 0 :this.variantParams.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof State) == false) {
            return false;
        }
        State rhs = ((State) other);
        return (((((this.name == rhs.name)||((this.name!= null)&&this.name.equals(rhs.name)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.params == rhs.params)||((this.params!= null)&&this.params.equals(rhs.params))))&&((this.variantParams == rhs.variantParams)||((this.variantParams!= null)&&this.variantParams.equals(rhs.variantParams))));
    }

}
