/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.contract.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * UpgradeFindings
 * <p>
 * What a v1-v4 pact conversion could not carry across exactly, and what it decided on the author's behalf (spec.md §8.4). Returned by 'upgrade/pact' alongside the converted contract (protocol spec §8.4) so 'pact upgrade' can show its work. An empty list is the claim that the conversion was exact.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "findings"
})
public class UpgradeFindings {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    private List<Finding> findings;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public List<Finding> getFindings() {
        return findings;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("findings")
    public void setFindings(List<Finding> findings) {
        this.findings = findings;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(UpgradeFindings.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("findings");
        sb.append('=');
        sb.append(((this.findings == null)?"<null>":this.findings));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.findings == null)? 0 :this.findings.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof UpgradeFindings) == false) {
            return false;
        }
        UpgradeFindings rhs = ((UpgradeFindings) other);
        return (((this.findings == rhs.findings)||((this.findings!= null)&&this.findings.equals(rhs.findings)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))));
    }

}
