/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Binding
 * <p>
 * One state parameter, resolved from the variant's point for one dimension (spec.md §6.4).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "cases",
    "default",
    "dimension",
    "name"
})
public class Binding {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("cases")
    private List<Case> cases;
    /**
     * The value when the dimension is inactive, or takes a point no case names. Required when the dimension is gated (spec.md §6.5). Absent with no matching case means the parameter is absent for that variant — not null.
     * 
     */
    @JsonProperty("default")
    @JsonPropertyDescription("The value when the dimension is inactive, or takes a point no case names. Required when the dimension is gated (spec.md \u00a76.5). Absent with no matching case means the parameter is absent for that variant \u2014 not null.")
    private Object _default;
    /**
     * A dimension reference: full id, full path, or a trailing run of whole path segments. Resolved by the engine at add-interaction and recorded resolved (spec.md §6.3).
     * (Required)
     * 
     */
    @JsonProperty("dimension")
    @JsonPropertyDescription("A dimension reference: full id, full path, or a trailing run of whole path segments. Resolved by the engine at add-interaction and recorded resolved (spec.md \u00a76.3).")
    private String dimension;
    /**
     * The state parameter this binds. MUST NOT also appear among the state's literal parameters.
     * (Required)
     * 
     */
    @JsonProperty("name")
    @JsonPropertyDescription("The state parameter this binds. MUST NOT also appear among the state's literal parameters.")
    private String name;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("cases")
    public List<Case> getCases() {
        return cases;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("cases")
    public void setCases(List<Case> cases) {
        this.cases = cases;
    }

    /**
     * The value when the dimension is inactive, or takes a point no case names. Required when the dimension is gated (spec.md §6.5). Absent with no matching case means the parameter is absent for that variant — not null.
     * 
     */
    @JsonProperty("default")
    public Object getDefault() {
        return _default;
    }

    /**
     * The value when the dimension is inactive, or takes a point no case names. Required when the dimension is gated (spec.md §6.5). Absent with no matching case means the parameter is absent for that variant — not null.
     * 
     */
    @JsonProperty("default")
    public void setDefault(Object _default) {
        this._default = _default;
    }

    /**
     * A dimension reference: full id, full path, or a trailing run of whole path segments. Resolved by the engine at add-interaction and recorded resolved (spec.md §6.3).
     * (Required)
     * 
     */
    @JsonProperty("dimension")
    public String getDimension() {
        return dimension;
    }

    /**
     * A dimension reference: full id, full path, or a trailing run of whole path segments. Resolved by the engine at add-interaction and recorded resolved (spec.md §6.3).
     * (Required)
     * 
     */
    @JsonProperty("dimension")
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    /**
     * The state parameter this binds. MUST NOT also appear among the state's literal parameters.
     * (Required)
     * 
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * The state parameter this binds. MUST NOT also appear among the state's literal parameters.
     * (Required)
     * 
     */
    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Binding.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("cases");
        sb.append('=');
        sb.append(((this.cases == null)?"<null>":this.cases));
        sb.append(',');
        sb.append("_default");
        sb.append('=');
        sb.append(((this._default == null)?"<null>":this._default));
        sb.append(',');
        sb.append("dimension");
        sb.append('=');
        sb.append(((this.dimension == null)?"<null>":this.dimension));
        sb.append(',');
        sb.append("name");
        sb.append('=');
        sb.append(((this.name == null)?"<null>":this.name));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.name == null)? 0 :this.name.hashCode()));
        result = ((result* 31)+((this._default == null)? 0 :this._default.hashCode()));
        result = ((result* 31)+((this.cases == null)? 0 :this.cases.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.dimension == null)? 0 :this.dimension.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Binding) == false) {
            return false;
        }
        Binding rhs = ((Binding) other);
        return ((((((this.name == rhs.name)||((this.name!= null)&&this.name.equals(rhs.name)))&&((this._default == rhs._default)||((this._default!= null)&&this._default.equals(rhs._default))))&&((this.cases == rhs.cases)||((this.cases!= null)&&this.cases.equals(rhs.cases))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.dimension == rhs.dimension)||((this.dimension!= null)&&this.dimension.equals(rhs.dimension))));
    }

}
