/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Coverage
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "covered",
    "dropped",
    "removed",
    "targets"
})
public class Coverage {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("covered")
    private Long covered;
    /**
     * Reachable targets the sampler could not complete without matching an exclusion; reported rather than searched for (spec.md §3.5).
     * 
     */
    @JsonProperty("dropped")
    @JsonPropertyDescription("Reachable targets the sampler could not complete without matching an exclusion; reported rather than searched for (spec.md \u00a73.5).")
    private Long dropped;
    /**
     * Targets removed because an exclusion makes them unreachable.
     * 
     */
    @JsonProperty("removed")
    @JsonPropertyDescription("Targets removed because an exclusion makes them unreachable.")
    private Long removed;
    /**
     * Reachable coverage targets at this strength, after exclusions (spec.md §3.3).
     * (Required)
     * 
     */
    @JsonProperty("targets")
    @JsonPropertyDescription("Reachable coverage targets at this strength, after exclusions (spec.md \u00a73.3).")
    private Long targets;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("covered")
    public Long getCovered() {
        return covered;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("covered")
    public void setCovered(Long covered) {
        this.covered = covered;
    }

    /**
     * Reachable targets the sampler could not complete without matching an exclusion; reported rather than searched for (spec.md §3.5).
     * 
     */
    @JsonProperty("dropped")
    public Long getDropped() {
        return dropped;
    }

    /**
     * Reachable targets the sampler could not complete without matching an exclusion; reported rather than searched for (spec.md §3.5).
     * 
     */
    @JsonProperty("dropped")
    public void setDropped(Long dropped) {
        this.dropped = dropped;
    }

    /**
     * Targets removed because an exclusion makes them unreachable.
     * 
     */
    @JsonProperty("removed")
    public Long getRemoved() {
        return removed;
    }

    /**
     * Targets removed because an exclusion makes them unreachable.
     * 
     */
    @JsonProperty("removed")
    public void setRemoved(Long removed) {
        this.removed = removed;
    }

    /**
     * Reachable coverage targets at this strength, after exclusions (spec.md §3.3).
     * (Required)
     * 
     */
    @JsonProperty("targets")
    public Long getTargets() {
        return targets;
    }

    /**
     * Reachable coverage targets at this strength, after exclusions (spec.md §3.3).
     * (Required)
     * 
     */
    @JsonProperty("targets")
    public void setTargets(Long targets) {
        this.targets = targets;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Coverage.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("covered");
        sb.append('=');
        sb.append(((this.covered == null)?"<null>":this.covered));
        sb.append(',');
        sb.append("dropped");
        sb.append('=');
        sb.append(((this.dropped == null)?"<null>":this.dropped));
        sb.append(',');
        sb.append("removed");
        sb.append('=');
        sb.append(((this.removed == null)?"<null>":this.removed));
        sb.append(',');
        sb.append("targets");
        sb.append('=');
        sb.append(((this.targets == null)?"<null>":this.targets));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.dropped == null)? 0 :this.dropped.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.removed == null)? 0 :this.removed.hashCode()));
        result = ((result* 31)+((this.targets == null)? 0 :this.targets.hashCode()));
        result = ((result* 31)+((this.covered == null)? 0 :this.covered.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Coverage) == false) {
            return false;
        }
        Coverage rhs = ((Coverage) other);
        return ((((((this.dropped == rhs.dropped)||((this.dropped!= null)&&this.dropped.equals(rhs.dropped)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.removed == rhs.removed)||((this.removed!= null)&&this.removed.equals(rhs.removed))))&&((this.targets == rhs.targets)||((this.targets!= null)&&this.targets.equals(rhs.targets))))&&((this.covered == rhs.covered)||((this.covered!= null)&&this.covered.equals(rhs.covered))));
    }

}
