/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SamplingPolicy
 * <p>
 * How an engine selects variants from a space (spec.md §3.8). Resolved in layers — specification defaults, session config, interaction spec, per-call override — with every member overriding, except 'pin' and 'exclude' which accumulate.
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "algorithm",
    "boundaries",
    "exclude",
    "exhaustive-threshold",
    "max-variants",
    "pin",
    "strategy",
    "strength"
})
public class SamplingPolicy {

    /**
     * The named selection algorithm (spec.md §3.7).
     * 
     */
    @JsonProperty("algorithm")
    @JsonPropertyDescription("The named selection algorithm (spec.md \u00a73.7).")
    private String algorithm;
    /**
     * Seed the minimal and maximal variants — each dimension at the point producing the least, respectively the most, structure (spec.md §3.1). They cost between zero and two variants, because the covering step works around a seed.
     * 
     */
    @JsonProperty("boundaries")
    @JsonPropertyDescription("Seed the minimal and maximal variants \u2014 each dimension at the point producing the least, respectively the most, structure (spec.md \u00a73.1). They cost between zero and two variants, because the covering step works around a seed.")
    private Boolean boundaries;
    /**
     * Regions removed from the space: never selected, never a coverage target, always reported with their reason (spec.md §3.5).
     * 
     */
    @JsonProperty("exclude")
    @JsonPropertyDescription("Regions removed from the space: never selected, never a coverage target, always reported with their reason (spec.md \u00a73.5).")
    private List<Exclusion> exclude;
    /**
     * Space size at or below which 'auto' selects every variant.
     * 
     */
    @JsonProperty("exhaustive-threshold")
    @JsonPropertyDescription("Space size at or below which 'auto' selects every variant.")
    private Long exhaustiveThreshold;
    /**
     * Largest selection the engine will return for one interaction. Exceeding it is 'variant-budget-exceeded', never a truncated selection (spec.md §3.6).
     * 
     */
    @JsonProperty("max-variants")
    @JsonPropertyDescription("Largest selection the engine will return for one interaction. Exceeding it is 'variant-budget-exceeded', never a truncated selection (spec.md \u00a73.6).")
    private Long maxVariants;
    /**
     * Partial assignments the selection must extend, in order, after the base variant.
     * 
     */
    @JsonProperty("pin")
    @JsonPropertyDescription("Partial assignments the selection must extend, in order, after the base variant.")
    private List<Pin> pin;
    /**
     * Default 'auto': exhaustive at or below 'exhaustive-threshold', t-wise above it (spec.md §3.2).
     * 
     */
    @JsonProperty("strategy")
    @JsonPropertyDescription("Default 'auto': exhaustive at or below 'exhaustive-threshold', t-wise above it (spec.md \u00a73.2).")
    private String strategy;
    /**
     * Covering strength for 't-wise'. 2 is pairwise, the default.
     * 
     */
    @JsonProperty("strength")
    @JsonPropertyDescription("Covering strength for 't-wise'. 2 is pairwise, the default.")
    private Long strength;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * The named selection algorithm (spec.md §3.7).
     * 
     */
    @JsonProperty("algorithm")
    public String getAlgorithm() {
        return algorithm;
    }

    /**
     * The named selection algorithm (spec.md §3.7).
     * 
     */
    @JsonProperty("algorithm")
    public void setAlgorithm(String algorithm) {
        this.algorithm = algorithm;
    }

    /**
     * Seed the minimal and maximal variants — each dimension at the point producing the least, respectively the most, structure (spec.md §3.1). They cost between zero and two variants, because the covering step works around a seed.
     * 
     */
    @JsonProperty("boundaries")
    public Boolean getBoundaries() {
        return boundaries;
    }

    /**
     * Seed the minimal and maximal variants — each dimension at the point producing the least, respectively the most, structure (spec.md §3.1). They cost between zero and two variants, because the covering step works around a seed.
     * 
     */
    @JsonProperty("boundaries")
    public void setBoundaries(Boolean boundaries) {
        this.boundaries = boundaries;
    }

    /**
     * Regions removed from the space: never selected, never a coverage target, always reported with their reason (spec.md §3.5).
     * 
     */
    @JsonProperty("exclude")
    public List<Exclusion> getExclude() {
        return exclude;
    }

    /**
     * Regions removed from the space: never selected, never a coverage target, always reported with their reason (spec.md §3.5).
     * 
     */
    @JsonProperty("exclude")
    public void setExclude(List<Exclusion> exclude) {
        this.exclude = exclude;
    }

    /**
     * Space size at or below which 'auto' selects every variant.
     * 
     */
    @JsonProperty("exhaustive-threshold")
    public Long getExhaustiveThreshold() {
        return exhaustiveThreshold;
    }

    /**
     * Space size at or below which 'auto' selects every variant.
     * 
     */
    @JsonProperty("exhaustive-threshold")
    public void setExhaustiveThreshold(Long exhaustiveThreshold) {
        this.exhaustiveThreshold = exhaustiveThreshold;
    }

    /**
     * Largest selection the engine will return for one interaction. Exceeding it is 'variant-budget-exceeded', never a truncated selection (spec.md §3.6).
     * 
     */
    @JsonProperty("max-variants")
    public Long getMaxVariants() {
        return maxVariants;
    }

    /**
     * Largest selection the engine will return for one interaction. Exceeding it is 'variant-budget-exceeded', never a truncated selection (spec.md §3.6).
     * 
     */
    @JsonProperty("max-variants")
    public void setMaxVariants(Long maxVariants) {
        this.maxVariants = maxVariants;
    }

    /**
     * Partial assignments the selection must extend, in order, after the base variant.
     * 
     */
    @JsonProperty("pin")
    public List<Pin> getPin() {
        return pin;
    }

    /**
     * Partial assignments the selection must extend, in order, after the base variant.
     * 
     */
    @JsonProperty("pin")
    public void setPin(List<Pin> pin) {
        this.pin = pin;
    }

    /**
     * Default 'auto': exhaustive at or below 'exhaustive-threshold', t-wise above it (spec.md §3.2).
     * 
     */
    @JsonProperty("strategy")
    public String getStrategy() {
        return strategy;
    }

    /**
     * Default 'auto': exhaustive at or below 'exhaustive-threshold', t-wise above it (spec.md §3.2).
     * 
     */
    @JsonProperty("strategy")
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }

    /**
     * Covering strength for 't-wise'. 2 is pairwise, the default.
     * 
     */
    @JsonProperty("strength")
    public Long getStrength() {
        return strength;
    }

    /**
     * Covering strength for 't-wise'. 2 is pairwise, the default.
     * 
     */
    @JsonProperty("strength")
    public void setStrength(Long strength) {
        this.strength = strength;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(SamplingPolicy.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("algorithm");
        sb.append('=');
        sb.append(((this.algorithm == null)?"<null>":this.algorithm));
        sb.append(',');
        sb.append("boundaries");
        sb.append('=');
        sb.append(((this.boundaries == null)?"<null>":this.boundaries));
        sb.append(',');
        sb.append("exclude");
        sb.append('=');
        sb.append(((this.exclude == null)?"<null>":this.exclude));
        sb.append(',');
        sb.append("exhaustiveThreshold");
        sb.append('=');
        sb.append(((this.exhaustiveThreshold == null)?"<null>":this.exhaustiveThreshold));
        sb.append(',');
        sb.append("maxVariants");
        sb.append('=');
        sb.append(((this.maxVariants == null)?"<null>":this.maxVariants));
        sb.append(',');
        sb.append("pin");
        sb.append('=');
        sb.append(((this.pin == null)?"<null>":this.pin));
        sb.append(',');
        sb.append("strategy");
        sb.append('=');
        sb.append(((this.strategy == null)?"<null>":this.strategy));
        sb.append(',');
        sb.append("strength");
        sb.append('=');
        sb.append(((this.strength == null)?"<null>":this.strength));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.exhaustiveThreshold == null)? 0 :this.exhaustiveThreshold.hashCode()));
        result = ((result* 31)+((this.pin == null)? 0 :this.pin.hashCode()));
        result = ((result* 31)+((this.strength == null)? 0 :this.strength.hashCode()));
        result = ((result* 31)+((this.maxVariants == null)? 0 :this.maxVariants.hashCode()));
        result = ((result* 31)+((this.boundaries == null)? 0 :this.boundaries.hashCode()));
        result = ((result* 31)+((this.exclude == null)? 0 :this.exclude.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.strategy == null)? 0 :this.strategy.hashCode()));
        result = ((result* 31)+((this.algorithm == null)? 0 :this.algorithm.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof SamplingPolicy) == false) {
            return false;
        }
        SamplingPolicy rhs = ((SamplingPolicy) other);
        return ((((((((((this.exhaustiveThreshold == rhs.exhaustiveThreshold)||((this.exhaustiveThreshold!= null)&&this.exhaustiveThreshold.equals(rhs.exhaustiveThreshold)))&&((this.pin == rhs.pin)||((this.pin!= null)&&this.pin.equals(rhs.pin))))&&((this.strength == rhs.strength)||((this.strength!= null)&&this.strength.equals(rhs.strength))))&&((this.maxVariants == rhs.maxVariants)||((this.maxVariants!= null)&&this.maxVariants.equals(rhs.maxVariants))))&&((this.boundaries == rhs.boundaries)||((this.boundaries!= null)&&this.boundaries.equals(rhs.boundaries))))&&((this.exclude == rhs.exclude)||((this.exclude!= null)&&this.exclude.equals(rhs.exclude))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.strategy == rhs.strategy)||((this.strategy!= null)&&this.strategy.equals(rhs.strategy))))&&((this.algorithm == rhs.algorithm)||((this.algorithm!= null)&&this.algorithm.equals(rhs.algorithm))));
    }

}
