/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SelectionReport
 * <p>
 * How the selection was chosen. Coverage figures are computed, never asserted (spec.md §3.3).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "algorithm",
    "boundaries",
    "budgets",
    "coverage",
    "exclusions",
    "notes",
    "selected",
    "space",
    "strategy",
    "strength"
})
public class SelectionReport {

    /**
     * The named selection algorithm (spec.md §3.7). A different algorithm is a different name, never a redefinition.
     * (Required)
     * 
     */
    @JsonProperty("algorithm")
    @JsonPropertyDescription("The named selection algorithm (spec.md \u00a73.7). A different algorithm is a different name, never a redefinition.")
    private String algorithm;
    /**
     * Whether the minimal and maximal variants were seeded (spec.md §3.1).
     * 
     */
    @JsonProperty("boundaries")
    @JsonPropertyDescription("Whether the minimal and maximal variants were seeded (spec.md \u00a73.1).")
    private Boolean boundaries;
    /**
     * Budgets
     * <p>
     * 
     * 
     */
    @JsonProperty("budgets")
    private Budgets budgets;
    /**
     * Coverage
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("coverage")
    private Coverage coverage;
    /**
     * The exclusions in force, each with the reason it carries and what it removed (spec.md §3.5).
     * 
     */
    @JsonProperty("exclusions")
    @JsonPropertyDescription("The exclusions in force, each with the reason it carries and what it removed (spec.md \u00a73.5).")
    private List<AppliedExclusion> exclusions;
    /**
     * Anything the selection needs to say for itself — a dropped target, a saturated count, a waiver.
     * 
     */
    @JsonProperty("notes")
    @JsonPropertyDescription("Anything the selection needs to say for itself \u2014 a dropped target, a saturated count, a waiver.")
    private List<Note> notes;
    /**
     * Number of variants in the selection; at least 1, because the base variant is unconditional.
     * (Required)
     * 
     */
    @JsonProperty("selected")
    @JsonPropertyDescription("Number of variants in the selection; at least 1, because the base variant is unconditional.")
    private Long selected;
    /**
     * SpaceSummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("space")
    private SpaceSummary space;
    /**
     * The strategy actually applied, after 'auto' resolved (spec.md §3.2).
     * (Required)
     * 
     */
    @JsonProperty("strategy")
    @JsonPropertyDescription("The strategy actually applied, after 'auto' resolved (spec.md \u00a73.2).")
    private String strategy;
    /**
     * Covering strength, for strategy 't-wise'.
     * 
     */
    @JsonProperty("strength")
    @JsonPropertyDescription("Covering strength, for strategy 't-wise'.")
    private Long strength;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * The named selection algorithm (spec.md §3.7). A different algorithm is a different name, never a redefinition.
     * (Required)
     * 
     */
    @JsonProperty("algorithm")
    public String getAlgorithm() {
        return algorithm;
    }

    /**
     * The named selection algorithm (spec.md §3.7). A different algorithm is a different name, never a redefinition.
     * (Required)
     * 
     */
    @JsonProperty("algorithm")
    public void setAlgorithm(String algorithm) {
        this.algorithm = algorithm;
    }

    /**
     * Whether the minimal and maximal variants were seeded (spec.md §3.1).
     * 
     */
    @JsonProperty("boundaries")
    public Boolean getBoundaries() {
        return boundaries;
    }

    /**
     * Whether the minimal and maximal variants were seeded (spec.md §3.1).
     * 
     */
    @JsonProperty("boundaries")
    public void setBoundaries(Boolean boundaries) {
        this.boundaries = boundaries;
    }

    /**
     * Budgets
     * <p>
     * 
     * 
     */
    @JsonProperty("budgets")
    public Budgets getBudgets() {
        return budgets;
    }

    /**
     * Budgets
     * <p>
     * 
     * 
     */
    @JsonProperty("budgets")
    public void setBudgets(Budgets budgets) {
        this.budgets = budgets;
    }

    /**
     * Coverage
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("coverage")
    public Coverage getCoverage() {
        return coverage;
    }

    /**
     * Coverage
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("coverage")
    public void setCoverage(Coverage coverage) {
        this.coverage = coverage;
    }

    /**
     * The exclusions in force, each with the reason it carries and what it removed (spec.md §3.5).
     * 
     */
    @JsonProperty("exclusions")
    public List<AppliedExclusion> getExclusions() {
        return exclusions;
    }

    /**
     * The exclusions in force, each with the reason it carries and what it removed (spec.md §3.5).
     * 
     */
    @JsonProperty("exclusions")
    public void setExclusions(List<AppliedExclusion> exclusions) {
        this.exclusions = exclusions;
    }

    /**
     * Anything the selection needs to say for itself — a dropped target, a saturated count, a waiver.
     * 
     */
    @JsonProperty("notes")
    public List<Note> getNotes() {
        return notes;
    }

    /**
     * Anything the selection needs to say for itself — a dropped target, a saturated count, a waiver.
     * 
     */
    @JsonProperty("notes")
    public void setNotes(List<Note> notes) {
        this.notes = notes;
    }

    /**
     * Number of variants in the selection; at least 1, because the base variant is unconditional.
     * (Required)
     * 
     */
    @JsonProperty("selected")
    public Long getSelected() {
        return selected;
    }

    /**
     * Number of variants in the selection; at least 1, because the base variant is unconditional.
     * (Required)
     * 
     */
    @JsonProperty("selected")
    public void setSelected(Long selected) {
        this.selected = selected;
    }

    /**
     * SpaceSummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("space")
    public SpaceSummary getSpace() {
        return space;
    }

    /**
     * SpaceSummary
     * <p>
     * 
     * (Required)
     * 
     */
    @JsonProperty("space")
    public void setSpace(SpaceSummary space) {
        this.space = space;
    }

    /**
     * The strategy actually applied, after 'auto' resolved (spec.md §3.2).
     * (Required)
     * 
     */
    @JsonProperty("strategy")
    public String getStrategy() {
        return strategy;
    }

    /**
     * The strategy actually applied, after 'auto' resolved (spec.md §3.2).
     * (Required)
     * 
     */
    @JsonProperty("strategy")
    public void setStrategy(String strategy) {
        this.strategy = strategy;
    }

    /**
     * Covering strength, for strategy 't-wise'.
     * 
     */
    @JsonProperty("strength")
    public Long getStrength() {
        return strength;
    }

    /**
     * Covering strength, for strategy 't-wise'.
     * 
     */
    @JsonProperty("strength")
    public void setStrength(Long strength) {
        this.strength = strength;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(SelectionReport.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("algorithm");
        sb.append('=');
        sb.append(((this.algorithm == null)?"<null>":this.algorithm));
        sb.append(',');
        sb.append("boundaries");
        sb.append('=');
        sb.append(((this.boundaries == null)?"<null>":this.boundaries));
        sb.append(',');
        sb.append("budgets");
        sb.append('=');
        sb.append(((this.budgets == null)?"<null>":this.budgets));
        sb.append(',');
        sb.append("coverage");
        sb.append('=');
        sb.append(((this.coverage == null)?"<null>":this.coverage));
        sb.append(',');
        sb.append("exclusions");
        sb.append('=');
        sb.append(((this.exclusions == null)?"<null>":this.exclusions));
        sb.append(',');
        sb.append("notes");
        sb.append('=');
        sb.append(((this.notes == null)?"<null>":this.notes));
        sb.append(',');
        sb.append("selected");
        sb.append('=');
        sb.append(((this.selected == null)?"<null>":this.selected));
        sb.append(',');
        sb.append("space");
        sb.append('=');
        sb.append(((this.space == null)?"<null>":this.space));
        sb.append(',');
        sb.append("strategy");
        sb.append('=');
        sb.append(((this.strategy == null)?"<null>":this.strategy));
        sb.append(',');
        sb.append("strength");
        sb.append('=');
        sb.append(((this.strength == null)?"<null>":this.strength));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.coverage == null)? 0 :this.coverage.hashCode()));
        result = ((result* 31)+((this.notes == null)? 0 :this.notes.hashCode()));
        result = ((result* 31)+((this.strength == null)? 0 :this.strength.hashCode()));
        result = ((result* 31)+((this.budgets == null)? 0 :this.budgets.hashCode()));
        result = ((result* 31)+((this.boundaries == null)? 0 :this.boundaries.hashCode()));
        result = ((result* 31)+((this.exclusions == null)? 0 :this.exclusions.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.strategy == null)? 0 :this.strategy.hashCode()));
        result = ((result* 31)+((this.selected == null)? 0 :this.selected.hashCode()));
        result = ((result* 31)+((this.space == null)? 0 :this.space.hashCode()));
        result = ((result* 31)+((this.algorithm == null)? 0 :this.algorithm.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof SelectionReport) == false) {
            return false;
        }
        SelectionReport rhs = ((SelectionReport) other);
        return ((((((((((((this.coverage == rhs.coverage)||((this.coverage!= null)&&this.coverage.equals(rhs.coverage)))&&((this.notes == rhs.notes)||((this.notes!= null)&&this.notes.equals(rhs.notes))))&&((this.strength == rhs.strength)||((this.strength!= null)&&this.strength.equals(rhs.strength))))&&((this.budgets == rhs.budgets)||((this.budgets!= null)&&this.budgets.equals(rhs.budgets))))&&((this.boundaries == rhs.boundaries)||((this.boundaries!= null)&&this.boundaries.equals(rhs.boundaries))))&&((this.exclusions == rhs.exclusions)||((this.exclusions!= null)&&this.exclusions.equals(rhs.exclusions))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.strategy == rhs.strategy)||((this.strategy!= null)&&this.strategy.equals(rhs.strategy))))&&((this.selected == rhs.selected)||((this.selected!= null)&&this.selected.equals(rhs.selected))))&&((this.space == rhs.space)||((this.space!= null)&&this.space.equals(rhs.space))))&&((this.algorithm == rhs.algorithm)||((this.algorithm!= null)&&this.algorithm.equals(rhs.algorithm))));
    }

}
