/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * SpaceSummary
 * <p>
 * 
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "dimensions",
    "exact",
    "size"
})
public class SpaceSummary {

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("dimensions")
    private Long dimensions;
    /**
     * False when counting saturated against the largest budget in force.
     * 
     */
    @JsonProperty("exact")
    @JsonPropertyDescription("False when counting saturated against the largest budget in force.")
    private Boolean exact;
    /**
     * Variants in the space, counted per spec.md §2.3. When 'exact' is false this is the saturation bound, meaning 'at least this many'.
     * (Required)
     * 
     */
    @JsonProperty("size")
    @JsonPropertyDescription("Variants in the space, counted per spec.md \u00a72.3. When 'exact' is false this is the saturation bound, meaning 'at least this many'.")
    private Long size;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("dimensions")
    public Long getDimensions() {
        return dimensions;
    }

    /**
     * 
     * (Required)
     * 
     */
    @JsonProperty("dimensions")
    public void setDimensions(Long dimensions) {
        this.dimensions = dimensions;
    }

    /**
     * False when counting saturated against the largest budget in force.
     * 
     */
    @JsonProperty("exact")
    public Boolean getExact() {
        return exact;
    }

    /**
     * False when counting saturated against the largest budget in force.
     * 
     */
    @JsonProperty("exact")
    public void setExact(Boolean exact) {
        this.exact = exact;
    }

    /**
     * Variants in the space, counted per spec.md §2.3. When 'exact' is false this is the saturation bound, meaning 'at least this many'.
     * (Required)
     * 
     */
    @JsonProperty("size")
    public Long getSize() {
        return size;
    }

    /**
     * Variants in the space, counted per spec.md §2.3. When 'exact' is false this is the saturation bound, meaning 'at least this many'.
     * (Required)
     * 
     */
    @JsonProperty("size")
    public void setSize(Long size) {
        this.size = size;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(SpaceSummary.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("dimensions");
        sb.append('=');
        sb.append(((this.dimensions == null)?"<null>":this.dimensions));
        sb.append(',');
        sb.append("exact");
        sb.append('=');
        sb.append(((this.exact == null)?"<null>":this.exact));
        sb.append(',');
        sb.append("size");
        sb.append('=');
        sb.append(((this.size == null)?"<null>":this.size));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.exact == null)? 0 :this.exact.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.size == null)? 0 :this.size.hashCode()));
        result = ((result* 31)+((this.dimensions == null)? 0 :this.dimensions.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof SpaceSummary) == false) {
            return false;
        }
        SpaceSummary rhs = ((SpaceSummary) other);
        return (((((this.exact == rhs.exact)||((this.exact!= null)&&this.exact.equals(rhs.exact)))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.size == rhs.size)||((this.size!= null)&&this.size.equals(rhs.size))))&&((this.dimensions == rhs.dimensions)||((this.dimensions!= null)&&this.dimensions.equals(rhs.dimensions))));
    }

}
