/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */


package io.pact.janus.bindings.variant.v1;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Variant
 * <p>
 * One variant. The assignment is the identity; the id is derived from it (spec.md §2.2).
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "assignment",
    "id",
    "label",
    "origin",
    "states"
})
public class Variant {

    /**
     * One point per active dimension, in variant-space order. Inactive dimensions are absent, never null.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    @JsonPropertyDescription("One point per active dimension, in variant-space order. Inactive dimensions are absent, never null.")
    private List<Point> assignment;
    /**
     * 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default, in variant-space order.
     * (Required)
     * 
     */
    @JsonProperty("id")
    @JsonPropertyDescription("'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default, in variant-space order.")
    private java.lang.String id;
    /**
     * Display only: the id with dimension ids shortened to the shortest unique trailing path segments. Never recorded in a pact file, never accepted where an id is expected (spec.md §2.2).
     * 
     */
    @JsonProperty("label")
    @JsonPropertyDescription("Display only: the id with dimension ids shortened to the shortest unique trailing path segments. Never recorded in a pact file, never accepted where an id is expected (spec.md \u00a72.2).")
    private java.lang.String label;
    /**
     * Why this variant is in the selection.
     * 
     */
    @JsonProperty("origin")
    @JsonPropertyDescription("Why this variant is in the selection.")
    private java.lang.String origin;
    /**
     * The interaction's provider states with this variant's parameters resolved (spec.md §6.4). The state document is design 2.5's.
     * 
     */
    @JsonProperty("states")
    @JsonPropertyDescription("The interaction's provider states with this variant's parameters resolved (spec.md \u00a76.4). The state document is design 2.5's.")
    private List<Map<String, Object>> states;
    @JsonIgnore
    private Map<java.lang.String, java.lang.Object> additionalProperties = new LinkedHashMap<java.lang.String, java.lang.Object>();

    /**
     * One point per active dimension, in variant-space order. Inactive dimensions are absent, never null.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    public List<Point> getAssignment() {
        return assignment;
    }

    /**
     * One point per active dimension, in variant-space order. Inactive dimensions are absent, never null.
     * (Required)
     * 
     */
    @JsonProperty("assignment")
    public void setAssignment(List<Point> assignment) {
        this.assignment = assignment;
    }

    /**
     * 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default, in variant-space order.
     * (Required)
     * 
     */
    @JsonProperty("id")
    public java.lang.String getId() {
        return id;
    }

    /**
     * 'base', or the ';'-joined '<dimension-id>=<point>' renderings of the dimensions that differ from their default, in variant-space order.
     * (Required)
     * 
     */
    @JsonProperty("id")
    public void setId(java.lang.String id) {
        this.id = id;
    }

    /**
     * Display only: the id with dimension ids shortened to the shortest unique trailing path segments. Never recorded in a pact file, never accepted where an id is expected (spec.md §2.2).
     * 
     */
    @JsonProperty("label")
    public java.lang.String getLabel() {
        return label;
    }

    /**
     * Display only: the id with dimension ids shortened to the shortest unique trailing path segments. Never recorded in a pact file, never accepted where an id is expected (spec.md §2.2).
     * 
     */
    @JsonProperty("label")
    public void setLabel(java.lang.String label) {
        this.label = label;
    }

    /**
     * Why this variant is in the selection.
     * 
     */
    @JsonProperty("origin")
    public java.lang.String getOrigin() {
        return origin;
    }

    /**
     * Why this variant is in the selection.
     * 
     */
    @JsonProperty("origin")
    public void setOrigin(java.lang.String origin) {
        this.origin = origin;
    }

    /**
     * The interaction's provider states with this variant's parameters resolved (spec.md §6.4). The state document is design 2.5's.
     * 
     */
    @JsonProperty("states")
    public List<Map<String, Object>> getStates() {
        return states;
    }

    /**
     * The interaction's provider states with this variant's parameters resolved (spec.md §6.4). The state document is design 2.5's.
     * 
     */
    @JsonProperty("states")
    public void setStates(List<Map<String, Object>> states) {
        this.states = states;
    }

    @JsonAnyGetter
    public Map<java.lang.String, java.lang.Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(java.lang.String name, java.lang.Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Variant.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("assignment");
        sb.append('=');
        sb.append(((this.assignment == null)?"<null>":this.assignment));
        sb.append(',');
        sb.append("id");
        sb.append('=');
        sb.append(((this.id == null)?"<null>":this.id));
        sb.append(',');
        sb.append("label");
        sb.append('=');
        sb.append(((this.label == null)?"<null>":this.label));
        sb.append(',');
        sb.append("origin");
        sb.append('=');
        sb.append(((this.origin == null)?"<null>":this.origin));
        sb.append(',');
        sb.append("states");
        sb.append('=');
        sb.append(((this.states == null)?"<null>":this.states));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.assignment == null)? 0 :this.assignment.hashCode()));
        result = ((result* 31)+((this.origin == null)? 0 :this.origin.hashCode()));
        result = ((result* 31)+((this.id == null)? 0 :this.id.hashCode()));
        result = ((result* 31)+((this.label == null)? 0 :this.label.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.states == null)? 0 :this.states.hashCode()));
        return result;
    }

    @Override
    public boolean equals(java.lang.Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Variant) == false) {
            return false;
        }
        Variant rhs = ((Variant) other);
        return (((((((this.assignment == rhs.assignment)||((this.assignment!= null)&&this.assignment.equals(rhs.assignment)))&&((this.origin == rhs.origin)||((this.origin!= null)&&this.origin.equals(rhs.origin))))&&((this.id == rhs.id)||((this.id!= null)&&this.id.equals(rhs.id))))&&((this.label == rhs.label)||((this.label!= null)&&this.label.equals(rhs.label))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.states == rhs.states)||((this.states!= null)&&this.states.equals(rhs.states))));
    }

}
