/*
 * Generated by tools/bindings from the spec schemas (plan task 6.1). Do not edit: regenerate with
 * `cargo run -p pact_janus_bindings -- generate`.
 */

package io.pact.janus.bindings.variant.v1;

import java.util.List;

/**
 * Known values of this package's open vocabularies. Values not listed here may appear and
 * must be handled by policy, never rejected (engine-protocol spec §2.2 rule 3).
 */
public final class Vocabulary {
  private Vocabulary() {}

  /** Known values of {@code Note.code}. */
  public static final class NoteCode {
    private NoteCode() {}

    public static final String TARGET_DROPPED = "target-dropped";
    public static final String SIZE_SATURATED = "size-saturated";
    public static final String BASE_ONLY_SELECTED = "base-only-selected";
    public static final String VARIANT_WAIVED = "variant-waived";

    public static final List<String> KNOWN = List.of(TARGET_DROPPED, SIZE_SATURATED, BASE_ONLY_SELECTED, VARIANT_WAIVED);
  }

  /** Known values of {@code SamplingPolicy.algorithm}. */
  public static final class SamplingPolicyAlgorithm {
    private SamplingPolicyAlgorithm() {}

    public static final String JANUS_IPOG_V1 = "janus-ipog-v1";

    public static final List<String> KNOWN = List.of(JANUS_IPOG_V1);
  }

  /** Known values of {@code SamplingPolicy.strategy}. */
  public static final class SamplingPolicyStrategy {
    private SamplingPolicyStrategy() {}

    public static final String AUTO = "auto";
    public static final String EXHAUSTIVE = "exhaustive";
    public static final String T_WISE = "t-wise";
    public static final String BASE_ONLY = "base-only";

    public static final List<String> KNOWN = List.of(AUTO, EXHAUSTIVE, T_WISE, BASE_ONLY);
  }

  /** Known values of {@code SelectionReport.algorithm}. */
  public static final class SelectionReportAlgorithm {
    private SelectionReportAlgorithm() {}

    public static final String JANUS_IPOG_V1 = "janus-ipog-v1";

    public static final List<String> KNOWN = List.of(JANUS_IPOG_V1);
  }

  /** Known values of {@code SelectionReport.strategy}. */
  public static final class SelectionReportStrategy {
    private SelectionReportStrategy() {}

    public static final String AUTO = "auto";
    public static final String EXHAUSTIVE = "exhaustive";
    public static final String T_WISE = "t-wise";
    public static final String BASE_ONLY = "base-only";

    public static final List<String> KNOWN = List.of(AUTO, EXHAUSTIVE, T_WISE, BASE_ONLY);
  }

  /** Known values of {@code Variant.origin}. */
  public static final class VariantOrigin {
    private VariantOrigin() {}

    public static final String BASE = "base";
    public static final String BOUNDARY = "boundary";
    public static final String PINNED = "pinned";
    public static final String COVERING = "covering";

    public static final List<String> KNOWN = List.of(BASE, BOUNDARY, PINNED, COVERING);
  }
}
