/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EngineErrorV2E1NewKnownValueE2NewField {
  code: string;
  message: string;
  details?: {
    [k: string]: unknown;
  };
  retryable?: boolean;
  [k: string]: unknown;
}
